# Brazil Teacher Pandemic Burnout Dataset Assessment

## Purpose
Initial screening and assessment of the Brazilian teacher pandemic burnout
dataset to determine its suitability for the early prediction of occupational
burnout risk using supervised machine learning.

In [1]:
import pandas as pd
import numpy as np

file_path = '/Users/cristinaabrahamse/Documents/Eduvos University/Data Science Honours /Early Prediction of Burnout (Honours Proj.)/Candidate Datasets/database_burnout_pandemia_brazil_translate.xlsx'

excel_file = pd.ExcelFile(file_path)

print("Sheet names:")
print(excel_file.sheet_names)

Sheet names:
['Data base', 'Subtitles (codes)', 'Open question']

### Workbook Structure

The Excel workbook contains three sheets:

- `Data base` – participant-level survey data.
- `Subtitles (codes)` – coding information/data dictionary.
- `Open question` – qualitative/open-ended responses.

For the current quantitative study, the primary focus will be the
participant-level `Data base` sheet and the accompanying coding information.

In [2]:
data = pd.read_excel(file_path, sheet_name="Data base")

data.head()

,Unnamed: 0,Unnamed: 1,doi: 10.5281/zenodo.7472241 https://zenodo.org/record/7472241,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 73,Unnamed: 74,Unnamed: 75,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82
0,Age:,Sex:,Marital status:,I live with:,Area of knowledge in which it operates:,Level of training (titration),Main level of education in which it operates:,Number of institutions or schools in which you...,The main institution(s) of activity are the ne...,Official or contractual weekly workload:,...,MBI -14I didn't worry about what happens to so...,MBI -15 I didn't worry about what happens to s...,MBI -16 I feel that I can easily create a plea...,MBI -17I feel motivated after working with my ...,MBI -18 I believe I get many valuable things i...,"MBI -19In the pandemic, I feel at the limit of...",MBI -20I think students blame me more for some...,MBI -final score,Have you had friends and/or close people who h...,Have you lost any friends or close people by C...
1,56,1,2,"My partner or wife/husband, Adult Son(s), Pet ...",1,6,5,2,2,5,...,2,3,1,2,2,2,NaN,38,1,1
2,40,1,2,"Partner or wife/husband, Son(s) who is a child(s)",2,6,5,1,2,4,...,4,0,4,4,2,2,0,34,1,2
3,56,1,1,Adult child(s),3,6,5,1,2,5,...,4,0,2,4,4,0,0,36,1,2
4,47,1,1,Alone,3,4,2,1,2,4,...,4,3,1,1,4,4,0,53,2,2

In [3]:
print("Raw dataset shape:", data.shape)

Raw dataset shape: (439, 83)

In [4]:
data.columns.tolist()

['Unnamed: 0',
 'Unnamed: 1',
 'doi: 10.5281/zenodo.7472241   https://zenodo.org/record/7472241',
 'Unnamed: 3',
 'Unnamed: 4',
 'Unnamed: 5',
 'Unnamed: 6',
 'Unnamed: 7',
 'Unnamed: 8',
 'Unnamed: 9',
 'Unnamed: 10',
 'Unnamed: 11',
 'Unnamed: 12',
 'Unnamed: 13',
 'Unnamed: 14',
 'Unnamed: 15',
 'Unnamed: 16',
 'Unnamed: 17',
 'Unnamed: 18',
 'Unnamed: 19',
 'Unnamed: 20',
 'Unnamed: 21',
 'Unnamed: 22',
 'Unnamed: 23',
 'Unnamed: 24',
 'Unnamed: 25',
 'Unnamed: 26',
 'Unnamed: 27',
 'Unnamed: 28',
 'Unnamed: 29',
 'Unnamed: 30',
 'Unnamed: 31',
 'Unnamed: 32',
 'Unnamed: 33',
 'Unnamed: 34',
 'Unnamed: 35',
 'Unnamed: 36',
 'Unnamed: 37',
 'Unnamed: 38',
 'Unnamed: 39',
 'Unnamed: 40',
 'Unnamed: 41',
 'Unnamed: 42',
 'Unnamed: 43',
 'Unnamed: 44',
 'Unnamed: 45',
 'Unnamed: 46',
 'Unnamed: 47',
 'Unnamed: 48',
 'Unnamed: 49',
 'Unnamed: 50',
 'Unnamed: 51',
 'Unnamed: 52',
 'Unnamed: 53',
 'Unnamed: 54',
 'Unnamed: 55',
 'Unnamed: 56',
 'Unnamed: 57',
 'Unnamed: 58',
 'Unnamed: 59',
 'Unnamed: 60',
 'Unnamed: 61',
 'Unnamed: 62',
 'Unnamed: 63',
 'Unnamed: 64',
 'Unnamed: 65',
 'Unnamed: 66',
 'Unnamed: 67',
 'Unnamed: 68',
 'Unnamed: 69',
 'Unnamed: 70',
 'Unnamed: 71',
 'Unnamed: 72',
 'Unnamed: 73',
 'Unnamed: 74',
 'Unnamed: 75',
 'Unnamed: 76',
 'Unnamed: 77',
 'Unnamed: 78',
 'Unnamed: 79',
 'Unnamed: 80',
 'Unnamed: 81',
 'Unnamed: 82']

In [5]:
print("Number of columns:", len(data.columns))

Number of columns: 83

In [6]:
# Display the first row containing the variable descriptions
pd.set_option("display.max_columns", None)

data.iloc[0]

Unnamed: 0                                                                                                      Age:
Unnamed: 1                                                                                                      Sex:
doi: 10.5281/zenodo.7472241   https://zenodo.org/record/7472241                                      Marital status:
Unnamed: 3                                                                                              I live with:
Unnamed: 4                                                                   Area of knowledge in which it operates:
                                                                                         ...
Unnamed: 78                                                        MBI -19In the pandemic, I feel at the limit of...
Unnamed: 79                                                        MBI -20I think students blame me more for some...
Unnamed: 80                                                                                         MBI -final score
Unnamed: 81                                                        Have you had friends and/or close people who h...
Unnamed: 82                                                        Have you lost any friends or close people by C...
Name: 0, Length: 83, dtype: object

In [7]:
codes = pd.read_excel(file_path, sheet_name="Subtitles (codes)", header=None)

print("Code sheet shape:", codes.shape)
codes.head(30)

Code sheet shape: (3, 83)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82
0,Age:,Sex:,Marital status:,I live with:,Area of knowledge in which it operates:,Level of training (titration),Main level of education in which it operates:,Number of institutions or schools in which you...,The main institution(s) of activity are the ne...,Official or contractual weekly workload:,Weekly workload effectively dedicated to work ...,Time of acting as a teacher:,Considering the devices and technological reso...,Considering the devices and technological reso...,Considerando os dispositivos e recursos tecnol...,Considerando os dispositivos e recursos tecnol...,Amount resource that has access,Considering the devices and technological reso...,Considering the devices and technological reso...,Internet connection,Considering your conditions of access to techn...,Considering your internet access conditions (c...,Conditions of access devices and internet,CD [Email account],CD [Instant communicators (e.g. whatsapp)],CD [Web conferencing or synchronous communicat...,"CD [Virtual learning environment (e.g. moodle,...","CD [Social networks (e.g. facebook, instagram ...",CD [Applications for editing digital text (e.g...,CD [Visual editing tools (e.g. power point or ...,CD [Tools for recording videos (e.g. digital c...,"CD [Tools for video editing (e.g. movavi, movi...",CD [Tools or resources for online activities (...,CD [Tools for interactive presentation (e.g. k...,digital competence score (CD),of new resources learned,CT - I have support from people who live with ...,CT - My co-workers assist me in the activities...,"CT - The institution or school offers support,...",CT - The technical(s) of the institution or sc...,CT - Received technical training for the use o...,CT - I received pedagogical training to work i...,"CT - Participated in courses, lives and/ or le...",CT - I dedicate more hours for planning in rem...,"CT - The process of evaluating learning, corre...",CT - I have difficulty using technological res...,CT - In my institution lack technological reso...,CT - Sinto-me sozinho na atuação no ensino remoto,CT - I missed being and interacting with stude...,working conditions (CT),QV [Sleep quality],QV [Amount of sleep hours],QV [Feed quality],QV [Body Weight],QV [Blood pressure],QV [Mood],QV [Anxiety],QV [Gastrointestinal problems],QV [Muscle pain],Sum quality of life score (QV),"MBI -1In the pandemic, I feel emotionally exha...",MBI -2I feel more tired at the end of the work...,MBI -3When I wake up in the morning and face a...,MBI -4In the pandemic I have easier to underst...,"MBI -5Now in the pandemic, I feel that working...",MBI -6I think I deal with my students' problem...,MBI -7I feel that my work in remote teaching i...,MBI -8I believe that with my work I am positiv...,MBI -9I've become more insensitive to people s...,MBI -10I feel that working in remote education...,MBI -11I feel very willing for my work in remo...,MBI -12I feel frustrated in my work in remote ...,MBI -13I feel like I'm working too the pandemi...,MBI -14I didn't worry about what happens to so...,MBI -15 I didn't worry about what happens to s...,MBI -16 I feel that I can easily create a plea...,MBI -17I feel motivated after working with my ...,MBI -18 I believe I get many valuable things i...,"MBI -19In the pandemic, I feel at the limit of...",MBI -20I think students blame me more for some...,MBI -final score,Have you had friends and/or close people who h...,Have you lost any friends or close people by C...
1,(in years),Female (1) Male (2),Single (1) Married or married (2) Divorced or ...,NaN,1-human /2-biological ) 3-Linguistica / 4 - he...,High school (1) Incomplete graduation (2) Comp...,ECE = Early Childhood Education (1); ES = Elem...,(in whole number),Private (1) Public (2),Up to 10 h per week (1) From 11 to 20 h per we...,Up to 10 h per week (1) From 11 to 20 h per we...,Up to 1 year (1) Between 1 and 5 years (2) Bet...,I have access (1) I do not have acc...,NaN,NaN,NaN,(sum of equipment you have access to),I have access (1) I do not have access (0),NaN,internet connection,"Scale from 1 to 5, where 1=""unsuitable"" and 5 ...",NaN,access conditions,Never used (0) I had never used and starte...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,competency total score,Amount you started using (sum of option 1),I totally disagree (1) - Partially disagree (2...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Working conditions - total score,Improved pandemic (1) No changes (0) ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Health total score,Never (1) - Annually (2) - Monthly (3) - Weekl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sum of the score of the 20 items of the MBI,Yes (1) No(2),NaN
2,* Questions/items in red had the assigned scor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Use the first row as the actual variable names
clean_data = data.copy()

clean_data.columns = clean_data.iloc[0]
clean_data = clean_data.iloc[1:].reset_index(drop=True)

print("Clean dataset shape:", clean_data.shape)
clean_data.head()

Clean dataset shape: (438, 83)

,Age:,Sex:,Marital status:,I live with:,Area of knowledge in which it operates:,Level of training (titration),Main level of education in which it operates:,Number of institutions or schools in which you act as a teacher:,The main institution(s) of activity are the network(s):,Official or contractual weekly workload:,Weekly workload effectively dedicated to work during pandemic,Time of acting as a teacher:,"Considering the devices and technological resources, indicate those to which you have (1) and do not have access (0): [Mobile]","Considering the devices and technological resources, indicate those you have (1) and do not have access (0): [Desktop computer]","Considerando os dispositivos e recursos tecnológicos, indique aqueles a que tem (1) e não tem acesso (0): [Computador portátil (notebook)]","Considerando os dispositivos e recursos tecnológicos, indique aqueles a que tem (1) e não tem acesso (0): [Tablet]",Amount resource that has access,"Considering the devices and technological resources, indicate those to which you have (1) and do not have access (0): [Home internet connection]","Considering the devices and technological resources, indicate those to which you have (1) and do not have access (0): [Internet connection by /on mobile]",Internet connection,"Considering your conditions of access to technologies, such as computer or notebook, you evaluate that these conditions are:","Considering your internet access conditions (cable and/or wi-fi), you assess that these conditions are:",Conditions of access devices and internet,CD [Email account],CD [Instant communicators (e.g. whatsapp)],"CD [Web conferencing or synchronous communication platform with video and sound (e.g. meet, zoom or skype)]","CD [Virtual learning environment (e.g. moodle, e-proinfo or google classroom)]","CD [Social networks (e.g. facebook, instagram or linkedin)]",CD [Applications for editing digital text (e.g. word or libreoffice)],CD [Visual editing tools (e.g. power point or canva)],CD [Tools for recording videos (e.g. digital cameras)],"CD [Tools for video editing (e.g. movavi, moviemaker or camtasia)]",CD [Tools or resources for online activities (e.g. online forum or questionnaire))],"CD [Tools for interactive presentation (e.g. kahoot, socrative or lied)]",digital competence score (CD),of new resources learned,CT - I have support from people who live with me in my residence,CT - My co-workers assist me in the activities necessary for remote teaching,"CT - The institution or school offers support, guidance and support for the development of remote education activities",CT - The technical(s) of the institution or school offers support for carrying out activities in the pandemic,CT - Received technical training for the use of technological resources,CT - I received pedagogical training to work in remote education,"CT - Participated in courses, lives and/ or lectures in addition to those offered by the institution(s) in which I work",CT - I dedicate more hours for planning in remote education than in face-to-face teaching,"CT - The process of evaluating learning, correcting and returning activities is more time-consuming in remote education",CT - I have difficulty using technological resources in remote education,CT - In my institution lack technological resources to develop activities in remote education,CT - Sinto-me sozinho na atuação no ensino remoto,CT - I missed being and interacting with students in the classroom in face-to-face teaching,working conditions (CT),QV [Sleep quality],QV [Amount of sleep hours],QV [Feed quality],QV [Body Weight],QV [Blood pressure],QV [Mood],QV [Anxiety],QV [Gastrointestinal problems],QV [Muscle pain],Sum quality of life score (QV),"MBI -1In the pandemic, I feel emotionally exhausted with my work [-]",MBI -2I feel more tired at the end of the working day than before the pandemic [-],"MBI -3When I wake up in the morning and face another day of work, I feel more tired than before the pandemic [-]",MBI -4In the pandemic I have easier to understand how my students feel [-],"MBI -5Now in the pandemic, I feel that working all day with students is a great effort and tire me more [-]",MBI -6I think I deal with my students' problems more effectively in remote teaching [-],MBI -7I feel that my work in remote teaching is wearing me down [-],MBI -8I believe that with my work I am positively influencing the lives of my students [+],MBI -9I've become more insensitive to people since I started teaching in the pandemic,MBI -10I feel that working in remote education is hardening me emotionally [-],MBI -11I feel very willing for my work in remote teaching [-],MBI -12I feel frustrated in my work in remote teaching [-],MBI -13I feel like I'm working too the pandemic [-],MBI -14I didn't worry about what happens to some students during the pandemic [-],MBI -15 I didn't worry about what happens to some students during the pandemic [-],MBI -16 I feel that I can easily create a pleasant atmosphere with my students in remote teaching [-],MBI -17I feel motivated after working with my students even remotely [-],MBI -18 I believe I get many valuable things in my job as a teacher in the pandemic [-],"MBI -19In the pandemic, I feel at the limit of my possibilities at work [-]",MBI -20I think students blame me more for some of their problems in remote teaching than in the face-to-face [-],MBI -final score,Have you had friends and/or close people who have contracted Covid 19?,Have you lost any friends or close people by Covid 19?
0,56,1,2,"My partner or wife/husband, Adult Son(s), Pet ...",1,6,5,2,2,5,4,5,1,0,1,0,2,1,1,2,5,5,10,2,2,2,2,2,2,2,2,1,2,1,20,2,5,4,4,0,2,2,3,3,3,3,3,3,3,38,0,0,-1,0,0,0,-1,0,-1,-3,0,0,4,4,3,1,3,0,3,NaN,1,3,4,2,3,1,2,2,2,NaN,38,1,1
1,40,1,2,"Partner or wife/husband, Son(s) who is a child(s)",2,6,5,1,2,4,3,2,1,0,1,0,2,1,1,2,4,5,9,2,2,1,2,2,2,2,1,1,1,0,16,4,5,5,4,4,4,4,1,1,2,3,1,3,1,38,0,0,0,0,0,-1,-1,0,0,-2,2,0,0,2,0,4,0,2,0,0,4,2,2,4,0,4,4,2,2,0,34,1,2
2,56,1,1,Adult child(s),3,6,5,1,2,5,6,5,1,0,1,0,2,1,1,2,3,4,7,2,2,1,1,2,2,2,0,0,1,0,13,3,4,3,2,1,3,2,4,1,1,2,3,1,1,28,-1,-1,-1,-1,-1,-1,-1,-1,-1,-9,2,2,2,0,2,2,2,4,0,0,4,0,2,4,0,2,4,4,0,0,36,1,2
3,47,1,1,Alone,3,4,2,1,2,4,3,5,1,0,1,0,2,1,1,2,2,3,5,2,2,1,1,2,1,2,2,0,1,0,14,4,5,4,2,3,4,4,4,1,2,4,4,1,1,39,-1,-1,1,1,0,-1,-1,0,0,-2,3,4,4,3,3,4,3,1,0,0,4,3,4,4,3,1,1,4,4,0,53,2,2
4,44,1,2,"Partner or wife/husband, Child(s) who is child...",8,5,5,1,2,2,2,4,1,0,1,1,3,1,1,2,5,4,9,2,2,2,2,2,2,2,2,0,2,0,18,0,4,4,3,3,1,2,4,4,3,5,5,3,3,44,-1,-1,0,0,0,0,0,0,0,-2,2,0,0,3,0,4,0,0,0,0,4,0,0,4,0,4,1,1,2,0,25,1,1

In [9]:
# Identify all MBI-related variables
mbi_columns = [
    col for col in clean_data.columns
    if "MBI" in str(col).upper()
]

print("Number of MBI variables:", len(mbi_columns))

for col in mbi_columns:
    print(col)

Number of MBI variables: 21
MBI -1In the pandemic, I feel emotionally exhausted with my work [-]
MBI -2I feel more tired at the end of the working day than before the pandemic [-]
MBI -3When I wake up in the morning and face another day of work, I feel more tired than before the pandemic [-]
MBI -4In the pandemic I have easier to understand how my students feel [-]
MBI -5Now in the pandemic, I feel that working all day with students is a great effort and tire me more [-]
MBI -6I think I deal with my students' problems more effectively in remote teaching [-]
MBI -7I feel that my work in remote teaching is wearing me down [-]
MBI -8I believe that with my work I am positively influencing the lives of my students [+]
MBI -9I've become more insensitive to people since I started teaching in the pandemic
MBI -10I feel that working in remote education is hardening me emotionally [-]
MBI -11I feel very willing for my work in remote teaching [-]
MBI -12I feel frustrated in my work in remote teaching [-]
MBI -13I feel like I'm working too the pandemic [-]
MBI -14I didn't worry about what happens to some students during the pandemic [-]
MBI -15 I didn't worry about what happens to some students during the pandemic [-]
MBI -16 I feel that I can easily create a pleasant atmosphere with my students in remote teaching [-]
MBI -17I feel motivated after working with my students even remotely [-]
MBI -18 I believe I get many valuable things in my job as a teacher in the pandemic [-]
MBI -19In the pandemic, I feel at the limit of my possibilities at work [-]
MBI -20I think students blame me more for some of their problems in remote teaching than in the face-to-face [-]
MBI -final score

In [13]:
# Examine the existing MBI final score
clean_data["MBI -final score"].value_counts(dropna=False).sort_index()

MBI -final score
6     1
11    2
13    3
14    2
15    2
     ..
68    1
69    5
70    3
71    1
72    2
Name: count, Length: 61, dtype: int64

In [15]:
# Check the data type and basic statistics
print(clean_data["MBI -final score"].dtype)

print(
    pd.to_numeric(
        clean_data["MBI -final score"],
        errors="coerce"
    ).describe()
)

object
count    438.000000
mean      42.440639
std       13.075906
min        6.000000
25%       34.000000
50%       41.000000
75%       53.000000
max       72.000000
Name: MBI -final score, dtype: float64

In [16]:
# Find the position of the MBI final score column
mbi_index = list(clean_data.columns).index("MBI -final score")

print("MBI final score column index:", mbi_index)

# Show everything from the code sheet for that column
print(codes.iloc[:, mbi_index])

MBI final score column index: 80
0                               MBI -final score
1    Sum of the score of the 20 items of the MBI
2                                            NaN
Name: 80, dtype: object

In [17]:
# Display the codebook information for the MBI section
codes.iloc[:, mbi_index-20:mbi_index+1]

,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80
0,"MBI -1In the pandemic, I feel emotionally exha...",MBI -2I feel more tired at the end of the work...,MBI -3When I wake up in the morning and face a...,MBI -4In the pandemic I have easier to underst...,"MBI -5Now in the pandemic, I feel that working...",MBI -6I think I deal with my students' problem...,MBI -7I feel that my work in remote teaching i...,MBI -8I believe that with my work I am positiv...,MBI -9I've become more insensitive to people s...,MBI -10I feel that working in remote education...,MBI -11I feel very willing for my work in remo...,MBI -12I feel frustrated in my work in remote ...,MBI -13I feel like I'm working too the pandemi...,MBI -14I didn't worry about what happens to so...,MBI -15 I didn't worry about what happens to s...,MBI -16 I feel that I can easily create a plea...,MBI -17I feel motivated after working with my ...,MBI -18 I believe I get many valuable things i...,"MBI -19In the pandemic, I feel at the limit of...",MBI -20I think students blame me more for some...,MBI -final score
1,Never (1) - Annually (2) - Monthly (3) - Weekl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sum of the score of the 20 items of the MBI
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
# Display all non-MBI variables
non_mbi_columns = [
    col for col in clean_data.columns
    if "MBI" not in str(col).upper()
]

print("Number of non-MBI variables:", len(non_mbi_columns))

for i, col in enumerate(non_mbi_columns, 1):
    print(f"{i}. {col}")

Number of non-MBI variables: 62
1. Age:
2. Sex:
3. Marital status:
4. I live with:
5. Area of knowledge in which it operates:
6. Level of training (titration)
7. Main level of education in which it operates:
8. Number of institutions or schools in which you act as a teacher:
9. The main institution(s) of activity are the network(s):
10. Official or contractual weekly workload:
11. Weekly workload effectively dedicated to work during pandemic
12. Time of acting as a teacher:
13. Considering the devices and technological resources, indicate those to which you have (1) and do not have access (0): [Mobile]
14. Considering the devices and technological resources, indicate those you have (1) and do not have access (0): [Desktop computer]
15. Considerando os dispositivos e recursos tecnológicos, indique aqueles a que tem (1) e não tem acesso (0): [Computador portátil (notebook)]
16. Considerando os dispositivos e recursos tecnológicos, indique aqueles a que tem (1) e não tem acesso (0): [Tablet]
17. Amount resource that has access
18. Considering the devices and technological resources, indicate those to which you have (1) and do not have access (0): [Home internet connection]
19. Considering the devices and technological resources, indicate those to which you have (1) and do not have access (0): [Internet connection by /on mobile]
20. Internet connection
21. Considering your conditions of access to technologies, such as computer or notebook, you evaluate that these conditions are:
22. Considering your internet access conditions (cable and/or wi-fi), you assess that these conditions are:
23. Conditions of access devices and internet
24. CD [Email account]
25. CD [Instant communicators (e.g. whatsapp)]
26. CD [Web conferencing or synchronous communication platform with video and sound (e.g. meet, zoom or skype)]
27. CD [Virtual learning environment (e.g. moodle, e-proinfo or google classroom)]
28. CD [Social networks (e.g. facebook, instagram or linkedin)]
29. CD [Applications for editing digital text (e.g. word or libreoffice)]
30. CD [Visual editing tools (e.g. power point or canva)]
31. CD [Tools for recording videos (e.g. digital cameras)]
32. CD [Tools for video editing (e.g. movavi, moviemaker or camtasia)]
33. CD [Tools or resources for online activities (e.g. online forum or questionnaire))]
34. CD [Tools for interactive presentation (e.g. kahoot, socrative or lied)]
35.  digital competence score (CD)
36.  of new resources learned
37. CT - I have support from people who live with me in my residence
38. CT - My co-workers assist me in the activities necessary for remote teaching
39. CT - The institution or school offers support, guidance and support for the development of remote education activities
40. CT - The technical(s) of the institution or school offers support for carrying out activities in the pandemic
41. CT - Received technical training for the use of technological resources
42. CT - I received pedagogical training to work in remote education
43. CT - Participated in courses, lives and/ or lectures in addition to those offered by the institution(s) in which I work
44. CT - I dedicate more hours for planning in remote education than in face-to-face teaching
45. CT - The process of evaluating learning, correcting and returning activities is more time-consuming in remote education
46. CT - I have difficulty using technological resources in remote education
47. CT - In my institution lack technological resources to develop activities in remote education
48. CT - Sinto-me sozinho na atuação no ensino remoto
49. CT - I missed being and interacting with students in the classroom in face-to-face teaching
50.  working conditions (CT)
51. QV [Sleep quality]
52. QV [Amount of sleep hours]
53. QV [Feed quality]
54. QV [Body Weight]
55. QV [Blood pressure]
56. QV [Mood]
57. QV [Anxiety]
58. QV [Gastrointestinal problems]
59. QV  [Muscle pain]
60. Sum quality of life score  (QV)
61. Have you had friends and/or close people who have contracted Covid 19?
62. Have you lost any friends or close people by Covid 19?

## Initial Dataset Assessment

**Decision: Strong candidate for primary supervised modelling.**

### Strengths
- Contains participant-level data for 438 teachers.
- Includes 20 MBI burnout items and an existing MBI final score.
- Contains substantial occupational and workplace-related information.
- Relevant workplace factors include workload, working hours, organisational
  support, coworker support, institutional resources, training, technological
  working conditions and teaching experience.
- Includes an accompanying coding/data dictionary sheet.
- The burnout outcome is available for all 438 participants.
- The MBI final score provides an independent burnout-related outcome that may
  later be operationalised into a binary burnout-risk target.

### Considerations
- The sample size is smaller than originally anticipated but remains potentially
  suitable for modelling and will be assessed alongside the other selected datasets.
- The data were collected within the specific context of remote teaching during
  the COVID-19 pandemic, which may limit generalisability.
- Several quality-of-life and mental-state variables are present but do not need
  to be included as primary workplace predictors.
- Individual MBI items must not be included as predictors if the MBI final score
  is used to construct the target variable, to avoid target leakage.
- The supplied documentation does not specify a binary risk threshold for the
  MBI final score. Binary target construction will therefore be addressed during
  the preprocessing stage using the common target-operationalisation strategy
  adopted across the final selected datasets.

### Overall Suitability
The dataset is highly relevant to the study because it combines an occupational
burnout measure with multiple workplace-related factors at participant level.
It should be retained as a strong candidate for primary modelling.