# Workplace Incivility, Emotional Exhaustion and Adaptive Performance

## Dataset Loading and Initial Inspection

This notebook analyses the Workplace Incivility dataset as part of the occupational burnout risk prediction study. The dataset is analysed independently using the common modelling framework applied across the selected secondary datasets.

Emotional exhaustion is used as the burnout-related outcome for this dataset, while workplace, occupational and demographic variables are assessed as potential predictors. Dataset-specific preprocessing is performed prior to applying the common interpretable machine learning framework.

In [2]:
# Load the Workplace Incivility dataset

import pandas as pd

file_path ='/Users/cristinaabrahamse/Documents/Eduvos University/Data Science Honours /Early Prediction of Burnout (Honours Proj.)/Candidate Datasets/Workplace incivility, emotional exhaustion and adaptive performance/WorkplaceIncivility.xlsx'

incivility = pd.read_excel(file_path)

print("Dataset shape:", incivility.shape)
incivility.head()

Dataset shape: (201, 58)

,ID,Age,Age_group,Gender,Marital_status,Race,Highest_education,Employment_sector,Rank,Tenure,...,EES,API,PA_Kecemasan,PA_Tekanan,PA_Kreatif,PA_Pembelajaran,PA_PenyesuaianPersonal,KetidaksopananTempatKerja,KeletihanEmosi,Level_WI
0,1,34,2,Lelaki,Berkahwin,Melayu,Diploma,Kesihata,Pelaksan,6-10 tah,...,36,78,14,18,18,12,16,35,36,3
1,2,32,2,Perempua,Bujang,Melayu,Ijazah S,Kesihata,Pelaksan,6-10 tah,...,33,85,19,16,22,13,15,17,33,1
2,3,34,2,Lelaki,Berkahwin,Melayu,Diploma,Kesihata,Pelaksan,11-15 ta,...,23,74,14,14,20,10,16,18,23,1
3,4,29,1,Perempua,Berkahwin,India,Ijazah S,Bekerja,Pelaksan,1-5 tahu,...,19,79,20,18,18,11,12,10,19,1
4,6,48,3,Perempua,Berkahwin,Melayu,Diploma,Kesihata,Pelaksan,20 tahun,...,22,92,16,22,22,15,17,11,22,1

## Initial Dataset Structure

The dataset structure, variable names, data types and missing values were inspected before preprocessing. This step was used to identify the available demographic, occupational, workplace and outcome-related variables and to determine whether any variables required translation, recoding or further validation.

In [3]:
# Inspect the dataset structure

print("Number of participants:", incivility.shape[0])
print("Number of variables:", incivility.shape[1])

print("\nVariables:")
for i, column in enumerate(incivility.columns, 1):
    print(f"{i}. {column}")

print("\nData types:")
print(incivility.dtypes)

print("\nMissing values:")
print(incivility.isnull().sum())

Number of participants: 201
Number of variables: 58

Variables:
1. ID
2. Age
3. Age_group
4. Gender
5. Marital_status
6. Race
7. Highest_education
8. Employment_sector
9. Rank
10. Tenure
11. Location
12. WIS.item1
13. WIS.item2
14. WIS.item3
15. WIS.item4
16. WIS.item5
17. WIS.item6
18. WIS.item7
19. EES.item1
20. EES.item2
21. EES.item3
22. EES.item4
23. EES.item5
24. EES.item6
25. EES.item7
26. EES.item8
27. EES.item9
28. API.item1
29. API.item2
30. API.item3
31. API.item4
32. API.item5
33. API.item6
34. API.item7
35. API.item8
36. API.item9
37. API.item10
38. API.item11
39. API.item12
40. API.item13
41. API.item14
42. API.item15
43. API.item16
44. API.item17
45. API.item18
46. API.item19
47. API.item20
48. WIS
49. EES
50. API
51. PA_Kecemasan
52. PA_Tekanan
53. PA_Kreatif
54. PA_Pembelajaran
55. PA_PenyesuaianPersonal
56. KetidaksopananTempatKerja
57. KeletihanEmosi
58. Level_WI

Data types:
ID                            int64
Age                           int64
Age_group                     int64
Gender                       object
Marital_status               object
Race                         object
Highest_education            object
Employment_sector            object
Rank                         object
Tenure                       object
Location                     object
WIS.item1                     int64
WIS.item2                     int64
WIS.item3                     int64
WIS.item4                     int64
WIS.item5                     int64
WIS.item6                     int64
WIS.item7                     int64
EES.item1                     int64
EES.item2                     int64
EES.item3                     int64
EES.item4                     int64
EES.item5                     int64
EES.item6                     int64
EES.item7                     int64
EES.item8                     int64
EES.item9                     int64
API.item1                     int64
API.item2                     int64
API.item3                     int64
API.item4                     int64
API.item5                     int64
API.item6                     int64
API.item7                     int64
API.item8                     int64
API.item9                     int64
API.item10                    int64
API.item11                    int64
API.item12                    int64
API.item13                    int64
API.item14                    int64
API.item15                    int64
API.item16                    int64
API.item17                    int64
API.item18                    int64
API.item19                    int64
API.item20                    int64
WIS                           int64
EES                           int64
API                           int64
PA_Kecemasan                  int64
PA_Tekanan                    int64
PA_Kreatif                    int64
PA_Pembelajaran               int64
PA_PenyesuaianPersonal        int64
KetidaksopananTempatKerja     int64
KeletihanEmosi                int64
Level_WI                      int64
dtype: object

Missing values:
ID                           0
Age                          0
Age_group                    0
Gender                       0
Marital_status               0
Race                         0
Highest_education            0
Employment_sector            0
Rank                         0
Tenure                       0
Location                     0
WIS.item1                    0
WIS.item2                    0
WIS.item3                    0
WIS.item4                    0
WIS.item5                    0
WIS.item6                    0
WIS.item7                    0
EES.item1                    0
EES.item2                    0
EES.item3                    0
EES.item4                    0
EES.item5                    0
EES.item6                    0
EES.item7                    0
EES.item8                    0
EES.item9                    0
API.item1                    0
API.item2                    0
API.item3                    0
API.item4                    0
API.item5                    0
API.item6                    0
API.item7                    0
API.item8                    0
API.item9                    0
API.item10                   0
API.item11                   0
API.item12                   0
API.item13                   0
API.item14                   0
API.item15                   0
API.item16                   0
API.item17                   0
API.item18                   0
API.item19                   0
API.item20                   0
WIS                          0
EES                          0
API                          0
PA_Kecemasan                 0
PA_Tekanan                   0
PA_Kreatif                   0
PA_Pembelajaran              0
PA_PenyesuaianPersonal       0
KetidaksopananTempatKerja    0
KeletihanEmosi               0
Level_WI                     0
dtype: int64

## Emotional Exhaustion Outcome Validation

The dataset contains nine Emotional Exhaustion Scale (EES) items together with a supplied EES composite score. Before constructing the harmonised burnout-related outcome, the supplied composite was validated against the underlying questionnaire items.

The EES represents emotional exhaustion as a burnout-related dimension rather than a complete multidimensional measure of occupational burnout.

In [4]:
# Validate the supplied EES score against the 9 questionnaire items

ees_items = [f"EES.item{i}" for i in range(1, 10)]

incivility["EES_Calculated"] = incivility[ees_items].sum(axis=1)

ees_matches = (
    incivility["EES_Calculated"] == incivility["EES"]
).sum()

print("Participants:", len(incivility))
print("Exact EES matches:", ees_matches)
print("Non-matches:", len(incivility) - ees_matches)

print("\nEES item ranges:")
print(incivility[ees_items].agg(["min", "max"]))

print("\nSupplied EES summary:")
print(incivility["EES"].describe())

Participants: 201
Exact EES matches: 201
Non-matches: 0

EES item ranges:
     EES.item1  EES.item2  EES.item3  EES.item4  EES.item5  EES.item6  \
min          1          1          1          1          1          1
max          5          5          5          5          5          5

     EES.item7  EES.item8  EES.item9
min          1          1          1
max          5          5          5

Supplied EES summary:
count    201.000000
mean      21.955224
std        7.932401
min        9.000000
25%       16.000000
50%       21.000000
75%       27.000000
max       45.000000
Name: EES, dtype: float64

**Outcome validation:**  
The supplied EES composite score was successfully validated against the nine Emotional Exhaustion Scale items. All 201 participants showed an exact match between the supplied score and the calculated item sum, with individual items ranging from 1 to 5 and total EES scores ranging from 9 to 45. The supplied EES score was therefore retained as the burnout-related outcome measure for subsequent analysis.

## Language and Coding Verification

The dataset contains English variable names alongside categorical responses and derived variables recorded in Malay. Before preprocessing, the unique values and coding structure of these variables were inspected.

Where translation was required, LLM-assisted interpretation was used alongside the available English questionnaire documentation. Final translations and variable meanings were researcher-validated against the questionnaire structure, observed values and dataset context before any variables were recoded or used for modelling.

In [5]:
# Inspect categorical values before translation or recoding

categorical_columns = [
    "Gender",
    "Marital_status",
    "Race",
    "Highest_education",
    "Employment_sector",
    "Rank",
    "Tenure",
    "Location"
]

for column in categorical_columns:
    print(f"\n--- {column} ---")
    print(incivility[column].value_counts(dropna=False))

--- Gender ---
Gender
Perempua    142
Lelaki       59
Name: count, dtype: int64

--- Marital_status ---
Marital_status
Berkahwin    135
Bujang        59
Duda/Jan       6
Berkahwi       1
Name: count, dtype: int64

--- Race ---
Race
Melayu      183
Cina          8
Lain-lai      6
India         4
Name: count, dtype: int64

--- Highest_education ---
Highest_education
Ijazah S    135
Diploma      38
SPM          19
Program       6
STPM          3
Name: count, dtype: int64

--- Employment_sector ---
Employment_sector
Kesihata    85
Pendidik    72
Perkhidm    22
Keselama    13
Pertania     2
Teknolog     2
Bekerja      1
Pembuata     1
Pembinaa     1
Perniaga     1
Industri     1
Name: count, dtype: int64

--- Rank ---
Rank
Pengurus    104
Pelaksan     97
Name: count, dtype: int64

--- Tenure ---
Tenure
1-5 tahu    59
6-10 tah    55
11-15 ta    50
20 tahun    28
16-20 ta     9
Name: count, dtype: int64

--- Location ---
Location
Bandar      158
Luar Ban     43
Name: count, dtype: int64

### Additional Derived Variable Inspection

Additional variables with Malay names were inspected separately to determine whether they represented existing questionnaire constructs, subscales or derived classifications. This was necessary to avoid duplicate information and potential target leakage during later predictor selection.

In [6]:
# Inspect additional derived variables

derived_columns = [
    "PA_Kecemasan",
    "PA_Tekanan",
    "PA_Kreatif",
    "PA_Pembelajaran",
    "PA_PenyesuaianPersonal",
    "KetidaksopananTempatKerja",
    "KeletihanEmosi",
    "Level_WI"
]

for column in derived_columns:
    print(f"\n--- {column} ---")
    print("Unique values:", sorted(incivility[column].unique()))
    print(incivility[column].value_counts().sort_index())

--- PA_Kecemasan ---
Unique values: [np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20)]
PA_Kecemasan
8      1
9      1
10     2
11     5
12    10
13     8
14    12
15    24
16    45
17    19
18    18
19    26
20    30
Name: count, dtype: int64

--- PA_Tekanan ---
Unique values: [np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25)]
PA_Tekanan
11     1
12     3
13     2
14     8
15    12
16    13
17    13
18    25
19    24
20    30
21    17
22    12
23    14
24    11
25    16
Name: count, dtype: int64

--- PA_Kreatif ---
Unique values: [np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25)]
PA_Kreatif
12     1
13     2
14     4
15    10
16     9
17    13
18    21
19    17
20    48
21    13
22    15
23    14
24    10
25    24
Name: count, dtype: int64

--- PA_Pembelajaran ---
Unique values: [np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15)]
PA_Pembelajaran
7      1
8      2
9     12
10    15
11    22
12    71
13    14
14     9
15    55
Name: count, dtype: int64

--- PA_PenyesuaianPersonal ---
Unique values: [np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20)]
PA_PenyesuaianPersonal
10     2
11     1
12    10
13     3
14    16
15    18
16    65
17    16
18    22
19    23
20    25
Name: count, dtype: int64

--- KetidaksopananTempatKerja ---
Unique values: [np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(28), np.int64(29), np.int64(32), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(40), np.int64(43)]
KetidaksopananTempatKerja
7     38
8     14
9     12
10    26
11    18
12     9
13     8
14     8
15     6
16     2
17     4
18     6
19     2
20     6
21     3
22     5
23     9
24     3
25     1
26     2
28     4
29     5
32     2
34     1
35     1
36     2
37     1
40     1
43     2
Name: count, dtype: int64

--- KeletihanEmosi ---
Unique values: [np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(34), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(45)]
KeletihanEmosi
9      9
10     2
11     7
12     7
13     8
14     6
15     4
16    11
17     4
18    17
19     9
20    11
21    13
22     8
23     9
24    12
25     2
26     4
27    14
28     1
29     3
30     4
31     4
32     3
33    10
34     4
35     1
36     4
37     2
38     6
39     1
45     1
Name: count, dtype: int64

--- Level_WI ---
Unique values: [np.int64(1), np.int64(2), np.int64(3)]
Level_WI
1    153
2     40
3      8
Name: count, dtype: int64

### Verification of Supplied Composite and Derived Scores

The dataset contains supplied composite and derived variables in addition to the individual questionnaire items. These variables were compared with the documented WIS, EES and API item scores to determine whether they represented duplicate totals, subscale scores or additional classifications.

This verification was performed before preprocessing to avoid retaining duplicate information or introducing target leakage into the modelling stage.

In [7]:
# Compare supplied composite and derived scores

checks = pd.DataFrame({
    "WIS": incivility["WIS"],
    "WIS_Calculated": incivility[[f"WIS.item{i}" for i in range(1, 8)]].sum(axis=1),

    "EES": incivility["EES"],
    "EES_Calculated": incivility[[f"EES.item{i}" for i in range(1, 10)]].sum(axis=1),

    "API": incivility["API"],
    "API_Calculated": incivility[[f"API.item{i}" for i in range(1, 21)]].sum(axis=1),

    "KetidaksopananTempatKerja": incivility["KetidaksopananTempatKerja"],
    "KeletihanEmosi": incivility["KeletihanEmosi"]
})

print("WIS exact matches:",
      (checks["WIS"] == checks["WIS_Calculated"]).sum(), "/ 201")

print("EES exact matches:",
      (checks["EES"] == checks["EES_Calculated"]).sum(), "/ 201")

print("API exact matches:",
      (checks["API"] == checks["API_Calculated"]).sum(), "/ 201")

print("\nWIS vs KetidaksopananTempatKerja:",
      (checks["WIS"] == checks["KetidaksopananTempatKerja"]).sum(), "/ 201")

print("EES vs KeletihanEmosi:",
      (checks["EES"] == checks["KeletihanEmosi"]).sum(), "/ 201")

WIS exact matches: 201 / 201
EES exact matches: 201 / 201
API exact matches: 0 / 201

WIS vs KetidaksopananTempatKerja: 201 / 201
EES vs KeletihanEmosi: 201 / 201

In [8]:
# Check how the supplied API score relates to the PA variables

pa_columns = [
    "PA_Kecemasan",
    "PA_Tekanan",
    "PA_Kreatif",
    "PA_Pembelajaran",
    "PA_PenyesuaianPersonal"
]

incivility["PA_Total_Calculated"] = incivility[pa_columns].sum(axis=1)

print("API summary:")
print(incivility["API"].describe())

print("\nCalculated PA total summary:")
print(incivility["PA_Total_Calculated"].describe())

print("\nAPI vs calculated PA total exact matches:",
      (incivility["API"] == incivility["PA_Total_Calculated"]).sum(),
      "/ 201")

print("\nFirst 10 comparisons:")
print(
    incivility[
        ["API"] + pa_columns + ["PA_Total_Calculated"]
    ].head(10)
)

API summary:
count    201.000000
mean      84.995025
std       10.823815
min       60.000000
25%       78.000000
50%       84.000000
75%       93.000000
max      105.000000
Name: API, dtype: float64

Calculated PA total summary:
count    201.000000
mean      84.995025
std       10.823815
min       60.000000
25%       78.000000
50%       84.000000
75%       93.000000
max      105.000000
Name: PA_Total_Calculated, dtype: float64

API vs calculated PA total exact matches: 201 / 201

First 10 comparisons:
   API  PA_Kecemasan  PA_Tekanan  PA_Kreatif  PA_Pembelajaran  \
0   78            14          18          18               12
1   85            19          16          22               13
2   74            14          14          20               10
3   79            20          18          18               11
4   92            16          22          22               15
5   83            20          14          16               15
6   83            16          19          20               12
7   86            16          17          20               13
8   62             8          12          17               11
9  103            20          25          25               15

   PA_PenyesuaianPersonal  PA_Total_Calculated
0                      16                   78
1                      15                   85
2                      16                   74
3                      12                   79
4                      17                   92
5                      18                   83
6                      16                   83
7                      20                   86
8                      14                   62
9                      18                  103

**Composite-score verification:**  
The supplied WIS and EES scores exactly matched the sums of their respective questionnaire items for all 201 participants. The Malay-named variables `KetidaksopananTempatKerja` and `KeletihanEmosi` were also exact duplicates of the supplied WIS and EES scores, respectively.

The supplied API score did not equal the direct sum of all 20 API items. Further inspection showed that API exactly equalled the sum of the five supplied `PA_` component scores for all 201 participants. These component scores were therefore recognised as derived adaptive-performance variables. Their precise item-level composition was not inferred where this was not explicitly documented in the available questionnaire.

In [9]:
# Create verified English mappings for clearly documented categories

language_mappings = {
    "Gender": {
        "Lelaki": "Male",
        "Perempua": "Female"
    },
    "Marital_status": {
        "Bujang": "Single",
        "Berkahwin": "Married",
        "Berkahwi": "Married",
        "Duda/Jan": "Divorced"
    },
    "Race": {
        "Melayu": "Malay",
        "Cina": "Chinese",
        "India": "Indian",
        "Lain-lai": "Other"
    },
    "Rank": {
        "Pelaksan": "Support",
        "Pengurus": "Professional and managerial"
    },
    "Location": {
        "Bandar": "Urban",
        "Luar Ban": "Rural"
    }
}

for column, mapping in language_mappings.items():
    print(f"\n--- {column} ---")
    for original, english in mapping.items():
        print(f"{original} -> {english}")

--- Gender ---
Lelaki -> Male
Perempua -> Female

--- Marital_status ---
Bujang -> Single
Berkahwin -> Married
Berkahwi -> Married
Duda/Jan -> Divorced

--- Race ---
Melayu -> Malay
Cina -> Chinese
India -> Indian
Lain-lai -> Other

--- Rank ---
Pelaksan -> Support
Pengurus -> Professional and managerial

--- Location ---
Bandar -> Urban
Luar Ban -> Rural

In [10]:
# Inspect remaining categorical variables before final recoding

remaining_categories = [
    "Highest_education",
    "Employment_sector",
    "Tenure"
]

for column in remaining_categories:
    print(f"\n--- {column} ---")
    
    values = (
        incivility[column]
        .value_counts()
        .rename_axis("Original_Value")
        .reset_index(name="Count")
    )
    
    print(values.to_string(index=False))

--- Highest_education ---
Original_Value  Count
      Ijazah S    135
       Diploma     38
           SPM     19
       Program      6
          STPM      3

--- Employment_sector ---
Original_Value  Count
      Kesihata     85
      Pendidik     72
      Perkhidm     22
      Keselama     13
      Pertania      2
      Teknolog      2
       Bekerja      1
      Pembuata      1
      Pembinaa      1
      Perniaga      1
      Industri      1

--- Tenure ---
Original_Value  Count
      1-5 tahu     59
      6-10 tah     55
      11-15 ta     50
      20 tahun     28
      16-20 ta      9

### Categorical Coding and Translation

Categorical variables were standardised into English using the available English questionnaire as the primary reference. Where the dataset contained truncated Malay response labels, their interpretation was checked against the questionnaire's documented response categories and the observed dataset structure.

Employment-sector responses outside the questionnaire's predefined categories were retained as separate translated categories at this stage rather than being automatically collapsed. Any later grouping of sparse categories was treated as a preprocessing decision rather than a translation decision.

In [11]:
# Create cleaned English categorical variables

incivility["Gender_English"] = incivility["Gender"].map({
    "Lelaki": "Male",
    "Perempua": "Female"
})

incivility["Marital_Status_English"] = incivility["Marital_status"].map({
    "Bujang": "Single",
    "Berkahwin": "Married",
    "Berkahwi": "Married",
    "Duda/Jan": "Divorced"
})

incivility["Race_English"] = incivility["Race"].map({
    "Melayu": "Malay",
    "Cina": "Chinese",
    "India": "Indian",
    "Lain-lai": "Other"
})

incivility["Education_English"] = incivility["Highest_education"].map({
    "SPM": "SPM",
    "STPM": "STPM",
    "Program": "Pre-University/Matriculation/Certificate",
    "Diploma": "Diploma",
    "Ijazah S": "Degree"
})

incivility["Rank_English"] = incivility["Rank"].map({
    "Pelaksan": "Support",
    "Pengurus": "Professional and managerial"
})

incivility["Tenure_English"] = incivility["Tenure"].map({
    "1-5 tahu": "1-5 years",
    "6-10 tah": "6-10 years",
    "11-15 ta": "11-15 years",
    "16-20 ta": "16-20 years",
    "20 tahun": ">20 years"
})

incivility["Location_English"] = incivility["Location"].map({
    "Bandar": "Urban",
    "Luar Ban": "Rural"
})

# Check that no values were lost during mapping
english_columns = [
    "Gender_English",
    "Marital_Status_English",
    "Race_English",
    "Education_English",
    "Rank_English",
    "Tenure_English",
    "Location_English"
]

print("Missing values after English mapping:")
print(incivility[english_columns].isnull().sum())

Missing values after English mapping:
Gender_English            0
Marital_Status_English    0
Race_English              0
Education_English         0
Rank_English              0
Tenure_English            0
Location_English          0
dtype: int64

In [12]:
# Translate and standardise employment-sector categories

incivility["Employment_Sector_English"] = incivility["Employment_sector"].map({
    "Kesihata": "Health",
    "Pendidik": "Education",
    "Perkhidm": "Services",
    "Keselama": "Security",
    "Pertania": "Agriculture",
    "Teknolog": "Technology",
    "Bekerja": "Other employment",
    "Pembuata": "Manufacturing",
    "Pembinaa": "Construction",
    "Perniaga": "Business",
    "Industri": "Industry"
})

print("Employment sector mapping:")
print(incivility["Employment_Sector_English"].value_counts(dropna=False))

print(
    "\nMissing after mapping:",
    incivility["Employment_Sector_English"].isnull().sum()
)

Employment sector mapping:
Employment_Sector_English
Health              85
Education           72
Services            22
Security            13
Agriculture          2
Technology           2
Other employment     1
Manufacturing        1
Construction         1
Business             1
Industry             1
Name: count, dtype: int64

Missing after mapping: 0

## Variable and Construct Assessment

The dataset contains demographic and occupational characteristics together with measures of workplace incivility, emotional exhaustion and adaptive performance. Supplied composite and derived variables were assessed against their underlying questionnaire constructs before predictor selection.

This step was used to distinguish original predictors, questionnaire items, composite scores, duplicate variables and derived classifications, reducing the risk of redundant information or target leakage during modelling.

In [13]:
# Inspect the relationship between WIS and Level_WI

level_wi_summary = (
    incivility.groupby("Level_WI")["WIS"]
    .agg(["count", "min", "max", "mean", "median"])
)

print("WIS scores by Level_WI:")
print(level_wi_summary)

print("\nLevel_WI distribution:")
print(incivility["Level_WI"].value_counts().sort_index())

WIS scores by Level_WI:
          count  min  max      mean  median
Level_WI
1           153    7   19  10.48366    10.0
2            40   20   32  24.25000    23.0
3             8   34   43  38.00000    36.5

Level_WI distribution:
Level_WI
1    153
2     40
3      8
Name: count, dtype: int64

**Derived workplace-incivility classification:**  
`Level_WI` was found to represent a categorical classification derived from the Workplace Incivility Scale (WIS). Participants classified as Level 1 had observed WIS scores between 7 and 19, Level 2 between 20 and 32, and Level 3 between 34 and 43. As `Level_WI` represents information already contained within the continuous WIS score, both variables were not treated as independent predictors simultaneously.

In [14]:
# Summarise the main variable families in the dataset

variable_families = {
    "Identifiers": ["ID"],

    "Demographic / Occupational": [
        "Age",
        "Age_group",
        "Gender_English",
        "Marital_Status_English",
        "Race_English",
        "Education_English",
        "Employment_Sector_English",
        "Rank_English",
        "Tenure_English",
        "Location_English"
    ],

    "Workplace Incivility": [
        *[f"WIS.item{i}" for i in range(1, 8)],
        "WIS",
        "KetidaksopananTempatKerja",
        "Level_WI"
    ],

    "Emotional Exhaustion": [
        *[f"EES.item{i}" for i in range(1, 10)],
        "EES",
        "KeletihanEmosi"
    ],

    "Adaptive Performance": [
        *[f"API.item{i}" for i in range(1, 21)],
        "PA_Kecemasan",
        "PA_Tekanan",
        "PA_Kreatif",
        "PA_Pembelajaran",
        "PA_PenyesuaianPersonal",
        "API"
    ]
}

for family, variables in variable_families.items():
    print(f"\n{family} ({len(variables)} variables)")
    for variable in variables:
        print(" -", variable)

Identifiers (1 variables)
 - ID

Demographic / Occupational (10 variables)
 - Age
 - Age_group
 - Gender_English
 - Marital_Status_English
 - Race_English
 - Education_English
 - Employment_Sector_English
 - Rank_English
 - Tenure_English
 - Location_English

Workplace Incivility (10 variables)
 - WIS.item1
 - WIS.item2
 - WIS.item3
 - WIS.item4
 - WIS.item5
 - WIS.item6
 - WIS.item7
 - WIS
 - KetidaksopananTempatKerja
 - Level_WI

Emotional Exhaustion (11 variables)
 - EES.item1
 - EES.item2
 - EES.item3
 - EES.item4
 - EES.item5
 - EES.item6
 - EES.item7
 - EES.item8
 - EES.item9
 - EES
 - KeletihanEmosi

Adaptive Performance (26 variables)
 - API.item1
 - API.item2
 - API.item3
 - API.item4
 - API.item5
 - API.item6
 - API.item7
 - API.item8
 - API.item9
 - API.item10
 - API.item11
 - API.item12
 - API.item13
 - API.item14
 - API.item15
 - API.item16
 - API.item17
 - API.item18
 - API.item19
 - API.item20
 - PA_Kecemasan
 - PA_Tekanan
 - PA_Kreatif
 - PA_Pembelajaran
 - PA_PenyesuaianPersonal
 - API

## LLM-Assisted Predictor Mapping and Researcher Validation

Following dataset and construct verification, variables were assessed according to their conceptual role in the study. LLM assistance was used to support semantic interpretation and grouping of heterogeneous variable names, including translated variables. These mappings were reviewed against the questionnaire documentation, observed dataset structure and study objectives before final researcher decisions were made.

Variables forming the emotional-exhaustion outcome were separated from candidate predictors to prevent target leakage. Duplicate variables and multiple representations of the same construct were also identified before final predictor selection.

In [15]:
# Create predictor-role audit

predictor_audit = pd.DataFrame([
    ["ID", "Identifier", "Exclude", "Participant identifier"],

    ["Age", "Demographics", "Candidate predictor", "Age in years"],
    ["Age_group", "Demographics", "Exclude", "Derived from Age"],

    ["Gender_English", "Demographics", "Candidate predictor", "Verified English category"],
    ["Marital_Status_English", "Demographics", "Candidate predictor", "Verified English category"],
    ["Race_English", "Demographics", "Candidate predictor", "Verified English category"],
    ["Education_English", "Employment characteristics", "Candidate predictor", "Education level"],
    ["Employment_Sector_English", "Employment characteristics", "Candidate predictor", "Employment sector"],
    ["Rank_English", "Employment characteristics", "Candidate predictor", "Occupational rank"],
    ["Tenure_English", "Employment characteristics", "Candidate predictor", "Employment tenure"],
    ["Location_English", "Demographics", "Candidate predictor", "Urban or rural location"],

    ["WIS", "Workplace incivility", "Candidate predictor", "Validated 7-item composite"],
    ["Level_WI", "Workplace incivility", "Exclude", "Derived classification of WIS"],

    ["EES", "Emotional exhaustion", "Outcome", "Burnout-related outcome composite"],
    ["KeletihanEmosi", "Emotional exhaustion", "Exclude", "Exact duplicate of EES"],

    ["API", "Adaptive performance", "Candidate predictor", "Overall adaptive-performance composite"],

    ["PA_Kecemasan", "Adaptive performance", "Exclude from primary model", "Component already represented by API"],
    ["PA_Tekanan", "Adaptive performance", "Exclude from primary model", "Component already represented by API"],
    ["PA_Kreatif", "Adaptive performance", "Exclude from primary model", "Component already represented by API"],
    ["PA_Pembelajaran", "Adaptive performance", "Exclude from primary model", "Component already represented by API"],
    ["PA_PenyesuaianPersonal", "Adaptive performance", "Exclude from primary model", "Component already represented by API"]
], columns=["Variable", "Conceptual_Group", "Proposed_Role", "Reason"])

predictor_audit

,Variable,Conceptual_Group,Proposed_Role,Reason
0,ID,Identifier,Exclude,Participant identifier
1,Age,Demographics,Candidate predictor,Age in years
2,Age_group,Demographics,Exclude,Derived from Age
3,Gender_English,Demographics,Candidate predictor,Verified English category
4,Marital_Status_English,Demographics,Candidate predictor,Verified English category
5,Race_English,Demographics,Candidate predictor,Verified English category
6,Education_English,Employment characteristics,Candidate predictor,Education level
7,Employment_Sector_English,Employment characteristics,Candidate predictor,Employment sector
8,Rank_English,Employment characteristics,Candidate predictor,Occupational rank
9,Tenure_English,Employment characteristics,Candidate predictor,Employment tenure
10,Location_English,Demographics,Candidate predictor,Urban or rural location
11,WIS,Workplace incivility,Candidate predictor,Validated 7-item composite
12,Level_WI,Workplace incivility,Exclude,Derived classification of WIS
13,EES,Emotional exhaustion,Outcome,Burnout-related outcome composite
14,KeletihanEmosi,Emotional exhaustion,Exclude,Exact duplicate of EES
15,API,Adaptive performance,Candidate predictor,Overall adaptive-performance composite
16,PA_Kecemasan,Adaptive performance,Exclude from primary model,Component already represented by API
17,PA_Tekanan,Adaptive performance,Exclude from primary model,Component already represented by API
18,PA_Kreatif,Adaptive performance,Exclude from primary model,Component already represented by API
19,PA_Pembelajaran,Adaptive performance,Exclude from primary model,Component already represented by API
20,PA_PenyesuaianPersonal,Adaptive performance,Exclude from primary model,Component already represented by API

### Researcher Validation of Predictor Mapping

The LLM-assisted variable mappings were manually reviewed against the English questionnaire, verified composite-score structure, translated categorical variables and the conceptual aims of the study. Final inclusion and exclusion decisions were made by the researcher rather than being determined automatically by the LLM.

Composite measures were preferred where they provided a documented and interpretable representation of a construct. Duplicate variables, derived classifications and individual questionnaire items already represented by retained composite scores were excluded to reduce redundancy. Variables forming the emotional-exhaustion outcome were reserved exclusively for outcome construction and were not eligible as predictors.

In [16]:
# Add researcher-validated decisions

predictor_audit["Researcher_Validated"] = "Yes"

predictor_audit["Final_Role"] = predictor_audit["Proposed_Role"]

predictor_audit[
    [
        "Variable",
        "Conceptual_Group",
        "Proposed_Role",
        "Researcher_Validated",
        "Final_Role",
        "Reason"
    ]
]

,Variable,Conceptual_Group,Proposed_Role,Researcher_Validated,Final_Role,Reason
0,ID,Identifier,Exclude,Yes,Exclude,Participant identifier
1,Age,Demographics,Candidate predictor,Yes,Candidate predictor,Age in years
2,Age_group,Demographics,Exclude,Yes,Exclude,Derived from Age
3,Gender_English,Demographics,Candidate predictor,Yes,Candidate predictor,Verified English category
4,Marital_Status_English,Demographics,Candidate predictor,Yes,Candidate predictor,Verified English category
5,Race_English,Demographics,Candidate predictor,Yes,Candidate predictor,Verified English category
6,Education_English,Employment characteristics,Candidate predictor,Yes,Candidate predictor,Education level
7,Employment_Sector_English,Employment characteristics,Candidate predictor,Yes,Candidate predictor,Employment sector
8,Rank_English,Employment characteristics,Candidate predictor,Yes,Candidate predictor,Occupational rank
9,Tenure_English,Employment characteristics,Candidate predictor,Yes,Candidate predictor,Employment tenure
10,Location_English,Demographics,Candidate predictor,Yes,Candidate predictor,Urban or rural location
11,WIS,Workplace incivility,Candidate predictor,Yes,Candidate predictor,Validated 7-item composite
12,Level_WI,Workplace incivility,Exclude,Yes,Exclude,Derived classification of WIS
13,EES,Emotional exhaustion,Outcome,Yes,Outcome,Burnout-related outcome composite
14,KeletihanEmosi,Emotional exhaustion,Exclude,Yes,Exclude,Exact duplicate of EES
15,API,Adaptive performance,Candidate predictor,Yes,Candidate predictor,Overall adaptive-performance composite
16,PA_Kecemasan,Adaptive performance,Exclude from primary model,Yes,Exclude from primary model,Component already represented by API
17,PA_Tekanan,Adaptive performance,Exclude from primary model,Yes,Exclude from primary model,Component already represented by API
18,PA_Kreatif,Adaptive performance,Exclude from primary model,Yes,Exclude from primary model,Component already represented by API
19,PA_Pembelajaran,Adaptive performance,Exclude from primary model,Yes,Exclude from primary model,Component already represented by API
20,PA_PenyesuaianPersonal,Adaptive performance,Exclude from primary model,Yes,Exclude from primary model,Component already represented by API

## Data Preprocessing and Cleaning

Following language verification, construct assessment and researcher validation, a processed copy of the dataset was created for subsequent analysis.

Original-language categorical variables were replaced in the analytical dataset by their verified English equivalents. Temporary variables created during composite-score validation were removed, while the original questionnaire items and supplied composite scores were retained where required for outcome construction, exploratory analysis and documentation.

No missing values were identified in the original dataset.

In [17]:

workplace = incivility.copy()

# Remove original categorical variables now represented by verified English versions
original_categories = [
    "Gender",
    "Marital_status",
    "Race",
    "Highest_education",
    "Employment_sector",
    "Rank",
    "Tenure",
    "Location"
]

# Remove temporary validation columns
temporary_columns = [
    "EES_Calculated",
    "PA_Total_Calculated"
]

columns_to_remove = [
    column for column in original_categories + temporary_columns
    if column in workplace.columns
]

workplace = workplace.drop(columns=columns_to_remove)

print("Processed dataset shape:", workplace.shape)
print("Missing values:", workplace.isnull().sum().sum())

Processed dataset shape: (201, 58)
Missing values: 0

## Burnout-Related Outcome Construction

Emotional exhaustion was used as the burnout-related outcome for this dataset. The supplied Emotional Exhaustion Scale (EES) consisted of nine items scored from 1 to 5 and was previously validated against the underlying questionnaire items for all participants.

To maintain a common outcome framework across the independently analysed datasets, the EES score was transformed to a 0–100 Harmonised Burnout Score (HBS) using the theoretical EES score range of 9 to 45.

The HBS provides a common interpretive scale across datasets while preserving the original scoring structure of the emotional-exhaustion measure.

In [18]:
# Transform EES to the common 0-100 HBS scale

workplace["HBS"] = (
    (workplace["EES"] - 9) / (45 - 9)
) * 100

print("HBS summary:")
print(workplace["HBS"].describe())

HBS summary:
count    201.000000
mean      35.986733
std       22.034447
min        0.000000
25%       19.444444
50%       33.333333
75%       50.000000
max      100.000000
Name: HBS, dtype: float64

### Elevated Burnout-Risk Classification

Consistent with the common modelling framework, the 75th percentile of the HBS distribution was used as the dataset-relative threshold for elevated burnout risk.

Participants with an HBS at or above the 75th-percentile threshold were classified as elevated risk (`1`), while participants below the threshold were classified as lower risk (`0`). This classification represents relative burnout-related risk within the dataset and should not be interpreted as a clinical diagnostic threshold.

In [19]:
# Create the elevated burnout-risk target using the 75th percentile

hbs_threshold = workplace["HBS"].quantile(0.75)

workplace["Burnout_Risk"] = (
    workplace["HBS"] >= hbs_threshold
).astype(int)

print("HBS elevated-risk threshold:", hbs_threshold)

print("\nBurnout-risk counts:")
print(workplace["Burnout_Risk"].value_counts().sort_index())

print("\nBurnout-risk percentages:")
print(
    workplace["Burnout_Risk"]
    .value_counts(normalize=True)
    .sort_index()
    .mul(100)
    .round(1)
)

HBS elevated-risk threshold: 50.0

Burnout-risk counts:
Burnout_Risk
0    143
1     58
Name: count, dtype: int64

Burnout-risk percentages:
Burnout_Risk
0    71.1
1    28.9
Name: proportion, dtype: float64

**Risk classification:**  
The 75th-percentile HBS threshold was 50.0. Using this dataset-relative threshold, 143 participants (71.1%) were classified as lower risk and 58 participants (28.9%) as elevated emotional-exhaustion/burnout risk. The elevated-risk proportion exceeded 25% because participants scoring exactly at the 75th-percentile threshold were included in the elevated-risk group.

## Pre-Modelling Exploratory Data Analysis

Exploratory data analysis was conducted before model development to examine the distributions and structure of the researcher-validated candidate predictors and their relationships with the burnout-risk outcome.

This stage was used to identify unusual values, sparse categories, differences between risk groups and potential issues requiring consideration before the final modelling matrix was constructed.

In [20]:
# Inspect numerical candidate predictors

numeric_candidates = [
    "Age",
    "WIS",
    "API"
]

print("Numerical predictor summary:")
print(
    workplace[numeric_candidates]
    .describe()
    .round(2)
)

print("\nMean values by burnout-risk group:")
print(
    workplace.groupby("Burnout_Risk")[numeric_candidates]
    .mean()
    .round(2)
)

Numerical predictor summary:
          Age     WIS     API
count  201.00  201.00  201.00
mean    35.61   14.32   85.00
std      7.92    8.01   10.82
min     22.00    7.00   60.00
25%     30.00    8.00   78.00
50%     35.00   11.00   84.00
75%     38.00   18.00   93.00
max     59.00   43.00  105.00

Mean values by burnout-risk group:
                Age    WIS    API
Burnout_Risk
0             35.99  12.19  86.22
1             34.67  19.57  81.98

In [21]:
# Inspect categorical candidate predictor distributions

categorical_candidates = [
    "Gender_English",
    "Marital_Status_English",
    "Race_English",
    "Education_English",
    "Employment_Sector_English",
    "Rank_English",
    "Tenure_English",
    "Location_English"
]

for column in categorical_candidates:
    print(f"\n--- {column} ---")
    print(workplace[column].value_counts())

--- Gender_English ---
Gender_English
Female    142
Male       59
Name: count, dtype: int64

--- Marital_Status_English ---
Marital_Status_English
Married     136
Single       59
Divorced      6
Name: count, dtype: int64

--- Race_English ---
Race_English
Malay      183
Chinese      8
Other        6
Indian       4
Name: count, dtype: int64

--- Education_English ---
Education_English
Degree                                      135
Diploma                                      38
SPM                                          19
Pre-University/Matriculation/Certificate      6
STPM                                          3
Name: count, dtype: int64

--- Employment_Sector_English ---
Employment_Sector_English
Health              85
Education           72
Services            22
Security            13
Agriculture          2
Technology           2
Other employment     1
Manufacturing        1
Construction         1
Business             1
Industry             1
Name: count, dtype: int64

--- Rank_English ---
Rank_English
Professional and managerial    104
Support                         97
Name: count, dtype: int64

--- Tenure_English ---
Tenure_English
1-5 years      59
6-10 years     55
11-15 years    50
>20 years      28
16-20 years     9
Name: count, dtype: int64

--- Location_English ---
Location_English
Urban    158
Rural     43
Name: count, dtype: int64

### Exploratory Comparison of Numerical Predictors

The distributions of key numerical candidate predictors were compared across the lower- and elevated-risk groups. These exploratory visualisations were used to assess whether workplace incivility, adaptive performance and age showed observable differences between the two risk classifications prior to model development.

In [22]:
import plotly.express as px

risk_labels = {
    0: "Lower Risk",
    1: "Elevated Risk"
}

workplace["Risk_Group"] = workplace["Burnout_Risk"].map(risk_labels)

fig = px.violin(
    workplace,
    x="Risk_Group",
    y="WIS",
    box=True,
    points="all",
    labels={
        "Risk_Group": "Burnout-Risk Group",
        "WIS": "Workplace Incivility Score"
    },
    title="Workplace Incivility by Burnout-Risk Group"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    height=550
)

fig.show()

**Interpretation:**  
Participants classified as elevated risk generally showed higher workplace incivility scores than those classified as lower risk. The elevated-risk group had a mean WIS score of 19.57 compared with 12.19 for the lower-risk group. Although the distributions overlap, the visual indicates a noticeable descriptive relationship between greater workplace incivility and elevated emotional-exhaustion risk. This relationship is exploratory and does not by itself establish predictive importance or causality.

In [23]:
# Compare adaptive performance across burnout-risk groups

fig = px.box(
    workplace,
    x="Risk_Group",
    y="API",
    points="all",
    labels={
        "Risk_Group": "Burnout-Risk Group",
        "API": "Adaptive Performance Score"
    },
    title="Adaptive Performance by Burnout-Risk Group"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    height=550
)

fig.show()

**Interpretation:**  
Participants classified as elevated risk showed somewhat lower adaptive performance scores than those classified as lower risk. Mean API scores were 81.98 for the elevated-risk group and 86.22 for the lower-risk group. However, considerable overlap was present between the distributions, suggesting that adaptive performance alone does not clearly distinguish the two risk groups. Its predictive contribution will therefore be assessed during model development.

In [24]:
# Examine elevated-risk percentage within categorical predictors

for column in categorical_candidates:
    risk_by_category = (
        workplace.groupby(column)["Burnout_Risk"]
        .agg(["count", "sum", "mean"])
        .rename(columns={
            "count": "Participants",
            "sum": "Elevated_Risk",
            "mean": "Elevated_Risk_Rate"
        })
    )

    risk_by_category["Elevated_Risk_Rate"] = (
        risk_by_category["Elevated_Risk_Rate"] * 100
    ).round(1)

    print(f"\n--- {column} ---")
    print(risk_by_category.sort_values("Elevated_Risk_Rate", ascending=False))

--- Gender_English ---
                Participants  Elevated_Risk  Elevated_Risk_Rate
Gender_English
Female                   142             41                28.9
Male                      59             17                28.8

--- Marital_Status_English ---
                        Participants  Elevated_Risk  Elevated_Risk_Rate
Marital_Status_English
Single                            59             19                32.2
Married                          136             38                27.9
Divorced                           6              1                16.7

--- Race_English ---
              Participants  Elevated_Risk  Elevated_Risk_Rate
Race_English
Other                    6              2                33.3
Malay                  183             55                30.1
Indian                   4              1                25.0
Chinese                  8              0                 0.0

--- Education_English ---
                                          Participants  Elevated_Risk  \
Education_English
Diploma                                             38             16
Pre-University/Matriculation/Certificate             6              2
STPM                                                 3              1
Degree                                             135             36
SPM                                                 19              3

                                          Elevated_Risk_Rate
Education_English
Diploma                                                 42.1
Pre-University/Matriculation/Certificate                33.3
STPM                                                    33.3
Degree                                                  26.7
SPM                                                     15.8

--- Employment_Sector_English ---
                           Participants  Elevated_Risk  Elevated_Risk_Rate
Employment_Sector_English
Construction                          1              1               100.0
Technology                            2              1                50.0
Health                               85             30                35.3
Services                             22              6                27.3
Education                            72             17                23.6
Security                             13              3                23.1
Agriculture                           2              0                 0.0
Business                              1              0                 0.0
Industry                              1              0                 0.0
Manufacturing                         1              0                 0.0
Other employment                      1              0                 0.0

--- Rank_English ---
                             Participants  Elevated_Risk  Elevated_Risk_Rate
Rank_English
Support                                97             33                34.0
Professional and managerial           104             25                24.0

--- Tenure_English ---
                Participants  Elevated_Risk  Elevated_Risk_Rate
Tenure_English
6-10 years                55             22                40.0
>20 years                 28              8                28.6
11-15 years               50             13                26.0
1-5 years                 59             15                25.4
16-20 years                9              0                 0.0

--- Location_English ---
                  Participants  Elevated_Risk  Elevated_Risk_Rate
Location_English
Urban                      158             47                29.7
Rural                       43             11                25.6

In [25]:
# Prepare elevated-risk rates by occupational rank

rank_risk = (
    workplace.groupby("Rank_English")["Burnout_Risk"]
    .mean()
    .mul(100)
    .reset_index(name="Elevated_Risk_Percentage")
)

fig = px.bar(
    rank_risk,
    x="Rank_English",
    y="Elevated_Risk_Percentage",
    text="Elevated_Risk_Percentage",
    labels={
        "Rank_English": "Occupational Rank",
        "Elevated_Risk_Percentage": "Elevated-Risk Participants (%)"
    },
    title="Elevated Burnout-Risk Rate by Occupational Rank"
)

fig.update_traces(
    texttemplate="%{text:.1f}%",
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    height=520,
    yaxis_range=[0, 45]
)

fig.show()

**Interpretation:**  
The elevated-risk rate was higher among participants in support roles (34.0%) than among those in professional and managerial roles (24.0%). This represents a descriptive difference within the sample and does not establish that occupational rank independently predicts elevated emotional-exhaustion risk. Its contribution will be assessed alongside the other predictors during modelling.

### Assessment of Sparse Categorical Levels

Categorical predictors were assessed for sparsely represented levels before model development. Very small categories can produce unstable one-hot encoded features, particularly in a relatively small dataset. Category frequencies were therefore reviewed before determining whether conceptually related low-frequency levels should be grouped for modelling.

In [26]:
# Identify categorical levels represented by fewer than 10 participants

for column in categorical_candidates:
    counts = workplace[column].value_counts()
    sparse = counts[counts < 10]

    if len(sparse) > 0:
        print(f"\n--- {column} ---")
        print(sparse)

--- Marital_Status_English ---
Marital_Status_English
Divorced    6
Name: count, dtype: int64

--- Race_English ---
Race_English
Chinese    8
Other      6
Indian     4
Name: count, dtype: int64

--- Education_English ---
Education_English
Pre-University/Matriculation/Certificate    6
STPM                                        3
Name: count, dtype: int64

--- Employment_Sector_English ---
Employment_Sector_English
Agriculture         2
Technology          2
Other employment    1
Manufacturing       1
Construction        1
Business            1
Industry            1
Name: count, dtype: int64

--- Tenure_English ---
Tenure_English
16-20 years    9
Name: count, dtype: int64

**Sparse-category decision:**  
Sparse levels were reviewed individually rather than automatically grouped using a frequency threshold. Employment sectors represented by very small numbers of participants were combined into an `Other` category to reduce unstable one-hot encoded features. The two small pre-tertiary education categories were also combined into a broader pre-tertiary category.

Race was excluded from the primary modelling predictor set because the sample was overwhelmingly represented by one racial group, leaving insufficient observations across the remaining categories for meaningful model estimation. Marital status and tenure categories were retained because they represented distinct questionnaire-defined categories despite some smaller group sizes.

In [27]:
# Group sparse employment-sector categories
main_sectors = ["Health", "Education", "Services", "Security"]

workplace["Employment_Sector_Grouped"] = (
    workplace["Employment_Sector_English"]
    .where(
        workplace["Employment_Sector_English"].isin(main_sectors),
        "Other"
    )
)

# Group the two small pre-tertiary education categories
education_mapping = {
    "STPM": "Pre-tertiary",
    "Pre-University/Matriculation/Certificate": "Pre-tertiary"
}

workplace["Education_Grouped"] = (
    workplace["Education_English"]
    .replace(education_mapping)
)

print("Employment sector:")
print(workplace["Employment_Sector_Grouped"].value_counts())

print("\nEducation:")
print(workplace["Education_Grouped"].value_counts())

Employment sector:
Employment_Sector_Grouped
Health       85
Education    72
Services     22
Security     13
Other         9
Name: count, dtype: int64

Education:
Education_Grouped
Degree          135
Diploma          38
SPM              19
Pre-tertiary      9
Name: count, dtype: int64

### Correlation and Redundancy Assessment

Relationships among the continuous candidate predictors were examined before model development to identify potential redundancy or strong linear associations. HBS was included in the exploratory correlation assessment only to examine its descriptive relationship with the candidate predictors and was not considered as a modelling predictor because it was used to construct the burnout-risk outcome.

In [28]:
# Examine correlations among continuous predictors and HBS

correlation_variables = [
    "Age",
    "WIS",
    "API",
    "HBS"
]

correlation_matrix = (
    workplace[correlation_variables]
    .corr()
    .round(2)
)

print(correlation_matrix)

      Age   WIS   API   HBS
Age  1.00 -0.20  0.13 -0.09
WIS -0.20  1.00 -0.24  0.42
API  0.13 -0.24  1.00 -0.26
HBS -0.09  0.42 -0.26  1.00

In [29]:
# Interactive correlation heatmap

fig = px.imshow(
    correlation_matrix,
    text_auto=".2f",
    aspect="auto",
    labels=dict(color="Correlation"),
    title="Correlation Matrix of Continuous Variables"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    height=520
)

fig.show()

**Interpretation:**  
Workplace incivility showed the strongest descriptive relationship with HBS (r = 0.42), indicating a moderate positive association with emotional exhaustion. Adaptive performance showed a weaker negative relationship with HBS (r = -0.26), while age showed little linear association (r = -0.09). Correlations among the continuous candidate predictors were relatively weak, with no indication of substantial redundancy between Age, WIS and API.

## Final Predictor Set and Modelling Data

Following construct validation, exploratory analysis and assessment of sparse categorical levels, the final predictor set was defined for model development.

The predictor set included demographic and occupational characteristics, workplace incivility and adaptive performance. Grouped versions of education and employment sector were used to reduce sparse categorical levels. Race was excluded from the primary modelling set because the sample was overwhelmingly represented by one racial group, resulting in insufficient representation across the remaining categories.

Variables used to construct the emotional-exhaustion outcome, including the EES items, EES score and HBS, were excluded from the predictor matrix to prevent target leakage.

In [30]:
# Define final predictor set and target

numeric_features = [
    "Age",
    "WIS",
    "API"
]

categorical_features = [
    "Gender_English",
    "Marital_Status_English",
    "Education_Grouped",
    "Employment_Sector_Grouped",
    "Rank_English",
    "Tenure_English",
    "Location_English"
]

final_predictors = numeric_features + categorical_features

X = workplace[final_predictors].copy()
y = workplace["Burnout_Risk"].copy()

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nFinal predictors:")
for predictor in final_predictors:
    print("-", predictor)

print("\nTarget distribution:")
print(y.value_counts().sort_index())

X shape: (201, 10)
y shape: (201,)

Final predictors:
- Age
- WIS
- API
- Gender_English
- Marital_Status_English
- Education_Grouped
- Employment_Sector_Grouped
- Rank_English
- Tenure_English
- Location_English

Target distribution:
Burnout_Risk
0    143
1     58
Name: count, dtype: int64

## Train-Test Split and Preprocessing

The dataset was divided into training and held-out test sets using an 80/20 split. Stratified sampling was applied to preserve the proportion of lower- and elevated-risk participants across both subsets.

A fixed random state was used to support reproducibility. All preprocessing and subsequent model fitting were performed using the training data, with the test set retained for final evaluation on previously unseen observations.

In [31]:
from sklearn.model_selection import train_test_split

# Create reproducible stratified training and test sets

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    stratify=y,
    random_state=42
)

print("Training set:", X_train.shape)
print("Test set:", X_test.shape)

print("\nTraining target:")
print(y_train.value_counts().sort_index())

print("\nTest target:")
print(y_test.value_counts().sort_index())

Training set: (160, 10)
Test set: (41, 10)

Training target:
Burnout_Risk
0    114
1     46
Name: count, dtype: int64

Test target:
Burnout_Risk
0    29
1    12
Name: count, dtype: int64

In [32]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# Preprocessing for numerical and categorical predictors

preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numeric_features
        ),
        (
            "cat",
            OneHotEncoder(handle_unknown="ignore"),
            categorical_features
        )
    ]
)

print("Numerical features:", numeric_features)
print("Categorical features:", categorical_features)

Numerical features: ['Age', 'WIS', 'API']
Categorical features: ['Gender_English', 'Marital_Status_English', 'Education_Grouped', 'Employment_Sector_Grouped', 'Rank_English', 'Tenure_English', 'Location_English']

## Baseline Model Development

Two interpretable supervised classification algorithms were initially evaluated: Logistic Regression and Decision Tree. These models were selected to provide complementary forms of interpretability, with Logistic Regression representing a linear probabilistic model and Decision Tree capturing potentially non-linear decision relationships.

The models were implemented within preprocessing pipelines to ensure that transformations were learned only from the relevant training data during model fitting and cross-validation. Class weighting was applied to account for the imbalance between the lower- and elevated-risk classes.

In [33]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

# Logistic Regression pipeline
lr_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(
        class_weight="balanced",
        max_iter=1000,
        random_state=42
    ))
])

# Decision Tree pipeline
dt_pipeline = Pipeline([
    ("preprocessor", preprocessor),
    ("model", DecisionTreeClassifier(
        class_weight="balanced",
        random_state=42
    ))
])

print("Baseline Logistic Regression and Decision Tree pipelines created.")

Baseline Logistic Regression and Decision Tree pipelines created.

### Baseline Cross-Validation

Baseline model performance was assessed using 5-fold stratified cross-validation on the training data. Stratification preserved the relative distribution of the lower- and elevated-risk classes within each fold.

Accuracy, precision, recall, F1-score and ROC-AUC were evaluated. Particular attention was given to recall and F1-score for the elevated-risk class because the study aims to identify individuals showing elevated burnout-related risk while maintaining balanced predictive performance.

In [34]:
from sklearn.model_selection import StratifiedKFold, cross_validate
import pandas as pd

# Define stratified 5-fold cross-validation
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

# Evaluation metrics
scoring = {
    "Accuracy": "accuracy",
    "Precision": "precision",
    "Recall": "recall",
    "F1": "f1",
    "ROC_AUC": "roc_auc"
}

# Evaluate baseline models
models = {
    "Logistic Regression": lr_pipeline,
    "Decision Tree": dt_pipeline
}

baseline_results = []

for model_name, model in models.items():
    scores = cross_validate(
        model,
        X_train,
        y_train,
        cv=cv,
        scoring=scoring
    )

    baseline_results.append({
        "Model": model_name,
        "Accuracy": scores["test_Accuracy"].mean(),
        "Precision": scores["test_Precision"].mean(),
        "Recall": scores["test_Recall"].mean(),
        "F1": scores["test_F1"].mean(),
        "ROC_AUC": scores["test_ROC_AUC"].mean()
    })

baseline_cv_results = pd.DataFrame(baseline_results)

print("Baseline 5-Fold Cross-Validation Results:")
print(
    baseline_cv_results
    .set_index("Model")
    .round(3)
)

Baseline 5-Fold Cross-Validation Results:
                     Accuracy  Precision  Recall     F1  ROC_AUC
Model
Logistic Regression     0.681      0.439   0.578  0.480    0.695
Decision Tree           0.669      0.437   0.391  0.409    0.586

**Baseline performance:**  
Logistic Regression showed stronger baseline cross-validation performance than the Decision Tree, particularly for recall (0.578), F1-score (0.480) and ROC-AUC (0.695). The Decision Tree achieved similar accuracy and precision but identified fewer elevated-risk cases across the validation folds. These results represent untuned baseline performance and were used as a reference for subsequent hyperparameter optimisation.

## Hyperparameter Tuning

Hyperparameter tuning was conducted using stratified 5-fold cross-validation on the training data. F1-score for the elevated-risk class was used as the primary optimisation criterion because it balances precision and recall while remaining appropriate for the moderately imbalanced outcome.

The held-out test set was not used during hyperparameter selection.

In [35]:
from sklearn.model_selection import GridSearchCV

# Hyperparameter grid for Logistic Regression
lr_param_grid = {
    "model__C": [0.01, 0.1, 1, 10, 100],
    "model__solver": ["liblinear", "lbfgs"]
}

lr_grid = GridSearchCV(
    estimator=lr_pipeline,
    param_grid=lr_param_grid,
    scoring="f1",
    cv=cv,
    n_jobs=-1
)

lr_grid.fit(X_train, y_train)

print("Best Logistic Regression parameters:")
print(lr_grid.best_params_)

print("\nBest cross-validation F1:")
print(round(lr_grid.best_score_, 3))

Best Logistic Regression parameters:
{'model__C': 0.01, 'model__solver': 'liblinear'}

Best cross-validation F1:
0.527

In [36]:
# Hyperparameter grid for Decision Tree

dt_param_grid = {
    "model__max_depth": [3, 5, 7, None],
    "model__min_samples_split": [2, 5, 10],
    "model__min_samples_leaf": [1, 2, 5, 10]
}

dt_grid = GridSearchCV(
    estimator=dt_pipeline,
    param_grid=dt_param_grid,
    scoring="f1",
    cv=cv,
    n_jobs=-1
)

dt_grid.fit(X_train, y_train)

print("Best Decision Tree parameters:")
print(dt_grid.best_params_)

print("\nBest cross-validation F1:")
print(round(dt_grid.best_score_, 3))

Best Decision Tree parameters:
{'model__max_depth': 5, 'model__min_samples_leaf': 10, 'model__min_samples_split': 2}

Best cross-validation F1:
0.59

### Tuned Model Cross-Validation

Following hyperparameter optimisation, the selected Logistic Regression and Decision Tree configurations were evaluated using the same stratified 5-fold cross-validation framework and performance metrics used for the baseline models.

This enabled comparison of model performance following optimisation before final evaluation on the held-out test set.

In [37]:
# Retrieve the tuned model pipelines

tuned_lr = lr_grid.best_estimator_
tuned_dt = dt_grid.best_estimator_

tuned_models = {
    "Tuned Logistic Regression": tuned_lr,
    "Tuned Decision Tree": tuned_dt
}

tuned_results = []

for model_name, model in tuned_models.items():
    scores = cross_validate(
        model,
        X_train,
        y_train,
        cv=cv,
        scoring=scoring
    )

    tuned_results.append({
        "Model": model_name,
        "Accuracy": scores["test_Accuracy"].mean(),
        "Precision": scores["test_Precision"].mean(),
        "Recall": scores["test_Recall"].mean(),
        "F1": scores["test_F1"].mean(),
        "ROC_AUC": scores["test_ROC_AUC"].mean()
    })

tuned_cv_results = pd.DataFrame(tuned_results)

print("Tuned 5-Fold Cross-Validation Results:")
print(
    tuned_cv_results
    .set_index("Model")
    .round(3)
)

Tuned 5-Fold Cross-Validation Results:
                           Accuracy  Precision  Recall     F1  ROC_AUC
Model
Tuned Logistic Regression     0.681      0.468   0.627  0.527    0.714
Tuned Decision Tree           0.744      0.530   0.689  0.590    0.758

**Tuned model performance:**  
Hyperparameter optimisation improved the cross-validation performance of both models. Logistic Regression improved from an F1-score of 0.480 to 0.527 and from a ROC-AUC of 0.695 to 0.714. The Decision Tree showed a larger improvement, increasing from an F1-score of 0.409 to 0.590 and from a ROC-AUC of 0.586 to 0.758. The tuned Decision Tree also achieved a recall of 0.689, indicating improved identification of elevated-risk observations across the validation folds. Final model performance was subsequently assessed using the untouched held-out test set.

In [38]:
# Combine baseline and tuned cross-validation results

cv_comparison = pd.concat(
    [baseline_cv_results, tuned_cv_results],
    ignore_index=True
)

cv_long = cv_comparison.melt(
    id_vars="Model",
    var_name="Metric",
    value_name="Score"
)

fig = px.bar(
    cv_long,
    x="Metric",
    y="Score",
    color="Model",
    barmode="group",
    text_auto=".2f",
    title="Baseline and Tuned Model Cross-Validation Performance"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    height=580,
    yaxis_title="Mean Cross-Validation Score",
    yaxis_range=[0, 1],
    legend_title="Model"
)

fig.show()

## Final Held-Out Test Evaluation

Following hyperparameter tuning, the tuned Logistic Regression and Decision Tree models were evaluated on the held-out test set, which had not been used during model training or hyperparameter selection.

Performance was assessed using accuracy, precision, recall, F1-score and ROC-AUC. Confusion matrices were also examined to determine the number of correctly identified and missed elevated-risk participants. Particular attention was given to recall because failure to identify elevated-risk cases represents an important consideration within an early-warning modelling context.

In [39]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix
)

# Evaluate tuned models on the held-out test set

test_results = []

for model_name, model in tuned_models.items():

    # Fit the selected model on the complete training set
    model.fit(X_train, y_train)

    # Predictions for the untouched test set
    y_pred = model.predict(X_test)
    y_prob = model.predict_proba(X_test)[:, 1]

    # Confusion matrix
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()

    test_results.append({
        "Model": model_name,
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1": f1_score(y_test, y_pred),
        "ROC_AUC": roc_auc_score(y_test, y_prob),
        "TN": tn,
        "FP": fp,
        "FN": fn,
        "TP": tp
    })

test_results_df = pd.DataFrame(test_results)

print("Held-Out Test Results:")
print(
    test_results_df
    .set_index("Model")
    .round(3)
)

Held-Out Test Results:
                           Accuracy  Precision  Recall    F1  ROC_AUC  TN  FP  \
Model
Tuned Logistic Regression     0.732      0.538   0.583  0.56    0.761  23   6
Tuned Decision Tree           0.707      0.500   0.500  0.50    0.757  23   6

                           FN  TP
Model
Tuned Logistic Regression   5   7
Tuned Decision Tree         6   6

### Extended Logistic Regression Optimisation

Following the initial tuning stage, an extended Logistic Regression optimisation was conducted using only the training data. The search examined different regularisation strengths and penalty types using stratified cross-validation.

This additional optimisation was performed without reference to the held-out test set to preserve its role as an independent evaluation sample.

In [40]:
# Extended Logistic Regression hyperparameter search

extended_lr_param_grid = [
    {
        "model__C": [0.001, 0.005, 0.01, 0.05, 0.1, 0.5, 1, 5, 10],
        "model__penalty": ["l1", "l2"],
        "model__solver": ["liblinear"]
    }
]

extended_lr_grid = GridSearchCV(
    estimator=lr_pipeline,
    param_grid=extended_lr_param_grid,
    scoring="f1",
    cv=cv,
    n_jobs=-1
)

extended_lr_grid.fit(X_train, y_train)

print("Best extended Logistic Regression parameters:")
print(extended_lr_grid.best_params_)

print("\nBest cross-validation F1:")
print(round(extended_lr_grid.best_score_, 3))

Best extended Logistic Regression parameters:
{'model__C': 0.5, 'model__penalty': 'l1', 'model__solver': 'liblinear'}

Best cross-validation F1:
0.539

In [41]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import precision_score, recall_score, f1_score
import numpy as np

# Use the extended tuned Logistic Regression
extended_tuned_lr = extended_lr_grid.best_estimator_

# Generate out-of-fold probabilities using training data only
oof_probabilities = cross_val_predict(
    extended_tuned_lr,
    X_train,
    y_train,
    cv=cv,
    method="predict_proba",
    n_jobs=-1
)[:, 1]

# Assess candidate probability thresholds
threshold_results = []

for threshold in np.arange(0.20, 0.81, 0.01):
    predictions = (oof_probabilities >= threshold).astype(int)

    threshold_results.append({
        "Threshold": threshold,
        "Precision": precision_score(y_train, predictions, zero_division=0),
        "Recall": recall_score(y_train, predictions, zero_division=0),
        "F1": f1_score(y_train, predictions, zero_division=0)
    })

threshold_results_df = pd.DataFrame(threshold_results)

best_threshold_row = threshold_results_df.loc[
    threshold_results_df["F1"].idxmax()
]

print("Best training-CV threshold:")
print(round(best_threshold_row["Threshold"], 2))

print("\nPerformance at selected threshold:")
print(best_threshold_row.round(3))

Best training-CV threshold:
0.49

Performance at selected threshold:
Threshold    0.490
Precision    0.500
Recall       0.652
F1           0.566
Name: 29, dtype: float64

In [42]:
# Fit the final Logistic Regression candidate on all training data
extended_tuned_lr.fit(X_train, y_train)

# Predict probabilities for the held-out test set
final_lr_prob = extended_tuned_lr.predict_proba(X_test)[:, 1]

# Apply the threshold selected using training CV only
final_lr_pred = (
    final_lr_prob >= best_threshold_row["Threshold"]
).astype(int)

# Calculate final held-out metrics
final_lr_accuracy = accuracy_score(y_test, final_lr_pred)
final_lr_precision = precision_score(y_test, final_lr_pred)
final_lr_recall = recall_score(y_test, final_lr_pred)
final_lr_f1 = f1_score(y_test, final_lr_pred)
final_lr_auc = roc_auc_score(y_test, final_lr_prob)

tn, fp, fn, tp = confusion_matrix(
    y_test,
    final_lr_pred
).ravel()

print("Extended Tuned Logistic Regression – Held-Out Test Results")
print("Accuracy:", round(final_lr_accuracy, 3))
print("Precision:", round(final_lr_precision, 3))
print("Recall:", round(final_lr_recall, 3))
print("F1:", round(final_lr_f1, 3))
print("ROC-AUC:", round(final_lr_auc, 3))

print("\nConfusion Matrix Counts:")
print("TN:", tn)
print("FP:", fp)
print("FN:", fn)
print("TP:", tp)

Extended Tuned Logistic Regression – Held-Out Test Results
Accuracy: 0.756
Precision: 0.571
Recall: 0.667
F1: 0.615
ROC-AUC: 0.779

Confusion Matrix Counts:
TN: 23
FP: 6
FN: 4
TP: 8

**Final Logistic Regression optimisation:**  
Extended optimisation of Logistic Regression selected L1 regularisation with C = 0.5 and the liblinear solver. Using out-of-fold predictions from the training data, a probability threshold of 0.49 was selected based on F1-score before final held-out evaluation.

On the held-out test set, the final Logistic Regression achieved an accuracy of 0.756, precision of 0.571, recall of 0.667, F1-score of 0.615 and ROC-AUC of 0.779. The model correctly identified 8 of the 12 elevated-risk participants and missed 4, while producing 6 false-positive classifications.

The improvement was achieved through optimisation conducted within the training data rather than adjustment based on held-out test performance. However, results should remain cautiously interpreted because the test set contained only 41 participants.

### Final Logistic Regression Confusion Matrix

The confusion matrix was examined to provide a direct representation of the final Logistic Regression model's classification performance on the held-out test set.

In [43]:
# Final Logistic Regression confusion matrix

final_lr_cm = confusion_matrix(
    y_test,
    final_lr_pred
)

fig = px.imshow(
    final_lr_cm,
    text_auto=True,
    x=["Predicted Lower Risk", "Predicted Elevated Risk"],
    y=["Actual Lower Risk", "Actual Elevated Risk"],
    labels=dict(
        x="Predicted Class",
        y="Actual Class",
        color="Participants"
    ),
    title="Final Logistic Regression – Held-Out Test Confusion Matrix"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    height=520
)

fig.show()

**Interpretation:**  
The final Logistic Regression correctly classified 23 lower-risk and 8 elevated-risk participants. Of the 12 participants who were actually classified as elevated risk, 8 were correctly identified and 4 were missed. Six lower-risk participants were incorrectly classified as elevated risk. This corresponds to a recall of 0.667, indicating that the model detected approximately two-thirds of the elevated-risk cases in the held-out sample.

In [44]:
# Final tuned Decision Tree confusion matrix

final_dt_pred = tuned_dt.predict(X_test)

final_dt_cm = confusion_matrix(
    y_test,
    final_dt_pred
)

fig = px.imshow(
    final_dt_cm,
    text_auto=True,
    x=["Predicted Lower Risk", "Predicted Elevated Risk"],
    y=["Actual Lower Risk", "Actual Elevated Risk"],
    labels=dict(
        x="Predicted Class",
        y="Actual Class",
        color="Participants"
    ),
    title="Tuned Decision Tree – Held-Out Test Confusion Matrix"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    height=520
)

fig.show()

**Interpretation:**  
The tuned Decision Tree correctly classified 23 lower-risk and 6 elevated-risk participants. Of the 12 participants who were actually classified as elevated risk, 6 were correctly identified and 6 were missed. Six lower-risk participants were incorrectly classified as elevated risk. This corresponds to a recall of 0.500, indicating that the model identified half of the elevated-risk cases in the held-out sample.

## Model Interpretability

Interpretability analysis was conducted to examine how the predictors contributed to model predictions. For Logistic Regression, model coefficients and corresponding odds ratios were extracted to examine the direction and relative magnitude of associations with elevated burnout-related risk.

For categorical predictors, coefficients represent the encoded category relative to the category omitted by the encoding process. Continuous predictors were standardised during preprocessing and should therefore be interpreted in relation to standardised changes rather than their original measurement units.

In [45]:
# Extract transformed feature names and Logistic Regression coefficients

final_preprocessor = extended_tuned_lr.named_steps["preprocessor"]
final_lr_model = extended_tuned_lr.named_steps["model"]

feature_names = final_preprocessor.get_feature_names_out()
coefficients = final_lr_model.coef_[0]

lr_interpretation = pd.DataFrame({
    "Feature": feature_names,
    "Coefficient": coefficients
})

lr_interpretation["Odds_Ratio"] = np.exp(
    lr_interpretation["Coefficient"]
)

lr_interpretation["Absolute_Coefficient"] = (
    lr_interpretation["Coefficient"].abs()
)

lr_interpretation = lr_interpretation.sort_values(
    "Absolute_Coefficient",
    ascending=False
)

print(
    lr_interpretation[
        ["Feature", "Coefficient", "Odds_Ratio"]
    ].round(3)
)

                                          Feature  Coefficient  Odds_Ratio
1                                        num__WIS        0.908       2.481
21                cat__Tenure_English_16-20 years       -0.258       0.772
22                 cat__Tenure_English_6-10 years        0.234       1.264
4                        cat__Gender_English_Male       -0.179       0.836
19                  cat__Tenure_English_1-5 years       -0.144       0.866
17  cat__Rank_English_Professional and managerial       -0.081       0.922
12       cat__Employment_Sector_Grouped_Education       -0.079       0.924
2                                        num__API       -0.060       0.942
13          cat__Employment_Sector_Grouped_Health        0.051       1.053
0                                        num__Age       -0.045       0.956
10            cat__Education_Grouped_Pre-tertiary        0.000       1.000
11                     cat__Education_Grouped_SPM        0.000       1.000
9                  cat__Education_Grouped_Diploma        0.000       1.000
8                   cat__Education_Grouped_Degree        0.000       1.000
14           cat__Employment_Sector_Grouped_Other        0.000       1.000
15        cat__Employment_Sector_Grouped_Security        0.000       1.000
16        cat__Employment_Sector_Grouped_Services        0.000       1.000
7              cat__Marital_Status_English_Single        0.000       1.000
18                      cat__Rank_English_Support        0.000       1.000
6             cat__Marital_Status_English_Married        0.000       1.000
20                cat__Tenure_English_11-15 years        0.000       1.000
5            cat__Marital_Status_English_Divorced        0.000       1.000
3                      cat__Gender_English_Female        0.000       1.000
23                  cat__Tenure_English_>20 years        0.000       1.000
24                    cat__Location_English_Rural        0.000       1.000
25                    cat__Location_English_Urban        0.000       1.000

### Logistic Regression Interpretation

The final Logistic Regression used L1 regularisation, which can shrink weak predictor coefficients exactly to zero. Non-zero coefficients were therefore examined to identify the encoded features retained by the fitted model.

Positive coefficients indicate an association with greater modelled odds of elevated risk, whereas negative coefficients indicate an association with lower modelled odds. Continuous predictors were standardised before model fitting; therefore, their coefficients and odds ratios correspond to a one-standard-deviation increase in the predictor.

Categorical coefficients are interpreted as contributions of the encoded categories within the fitted predictive model rather than conventional reference-category odds ratios because all categorical levels were retained during one-hot encoding.

In [46]:
# Retain features with non-zero coefficients selected by L1 regularisation

lr_nonzero = lr_interpretation[
    lr_interpretation["Coefficient"].abs() > 1e-6
].copy()

lr_nonzero = lr_nonzero[
    ["Feature", "Coefficient", "Odds_Ratio"]
].sort_values(
    "Coefficient",
    ascending=False
)

print("Non-zero Logistic Regression coefficients:")
print(lr_nonzero.round(3))

Non-zero Logistic Regression coefficients:
                                          Feature  Coefficient  Odds_Ratio
1                                        num__WIS        0.908       2.481
22                 cat__Tenure_English_6-10 years        0.234       1.264
13          cat__Employment_Sector_Grouped_Health        0.051       1.053
0                                        num__Age       -0.045       0.956
2                                        num__API       -0.060       0.942
12       cat__Employment_Sector_Grouped_Education       -0.079       0.924
17  cat__Rank_English_Professional and managerial       -0.081       0.922
19                  cat__Tenure_English_1-5 years       -0.144       0.866
4                        cat__Gender_English_Male       -0.179       0.836
21                cat__Tenure_English_16-20 years       -0.258       0.772

In [47]:
# Clean feature names for visualisation

lr_plot = lr_nonzero.copy()

lr_plot["Feature_Label"] = (
    lr_plot["Feature"]
    .str.replace("num__", "", regex=False)
    .str.replace("cat__", "", regex=False)
    .str.replace("_", " ", regex=False)
)

# Sort from negative to positive coefficient
lr_plot = lr_plot.sort_values("Coefficient")

fig = px.bar(
    lr_plot,
    x="Coefficient",
    y="Feature_Label",
    orientation="h",
    text="Coefficient",
    labels={
        "Coefficient": "Logistic Regression Coefficient",
        "Feature_Label": "Predictor"
    },
    title="Non-Zero Predictors Retained by Final Logistic Regression"
)

fig.update_traces(
    texttemplate="%{text:.2f}",
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    height=600,
    yaxis_title="",
    xaxis_title="Coefficient"
)

fig.add_vline(
    x=0,
    line_dash="dash"
)

fig.show()

**Interpretation:**  
Workplace incivility (WIS) was the strongest predictor retained by the final L1-regularised Logistic Regression, with a positive coefficient of 0.908 and an odds ratio of 2.481. Because WIS was standardised before modelling, a one-standard-deviation increase in workplace incivility corresponded to approximately 2.48 times the modelled odds of elevated emotional-exhaustion risk, holding the other encoded features constant.

The remaining retained coefficients were substantially smaller. L1 regularisation also reduced several encoded feature coefficients to zero, indicating that they contributed little to the final linear decision function. The categorical coefficients are interpreted as contributions within the fitted predictive model rather than conventional reference-category comparisons.

### Decision Tree Feature Importance

Feature importance was extracted from the tuned Decision Tree to examine which predictors contributed most strongly to its classification decisions. Importance values represent the relative contribution of each encoded feature to reducing classification impurity across the fitted tree and should not be interpreted as causal effects.

In [48]:
# Extract Decision Tree feature importances

dt_preprocessor = tuned_dt.named_steps["preprocessor"]
dt_model = tuned_dt.named_steps["model"]

dt_feature_names = dt_preprocessor.get_feature_names_out()
dt_importances = dt_model.feature_importances_

dt_importance_df = pd.DataFrame({
    "Feature": dt_feature_names,
    "Importance": dt_importances
})

dt_importance_df = (
    dt_importance_df
    .sort_values("Importance", ascending=False)
)

# Show features actually used by the tree
dt_used_features = dt_importance_df[
    dt_importance_df["Importance"] > 0
].copy()

print("Decision Tree features with non-zero importance:")
print(dt_used_features.round(3))

Decision Tree features with non-zero importance:
                                          Feature  Importance
1                                        num__WIS       0.514
19                  cat__Tenure_English_1-5 years       0.172
0                                        num__Age       0.115
3                      cat__Gender_English_Female       0.109
17  cat__Rank_English_Professional and managerial       0.043
25                    cat__Location_English_Urban       0.033
2                                        num__API       0.013

**Interpretation:**  
Workplace incivility (WIS) was the most influential feature in the tuned Decision Tree, accounting for 51.4% of the model's total impurity-based feature importance. Tenure of 1–5 years (17.2%), age (11.5%) and female gender (10.9%) also contributed to the tree's classification decisions, while occupational rank, location and adaptive performance showed smaller contributions.

The prominence of WIS was consistent with the Logistic Regression interpretation, in which workplace incivility also showed the strongest retained coefficient. This cross-model pattern suggests that workplace incivility was an important predictive feature for elevated emotional-exhaustion risk within this dataset. Feature importance represents predictive contribution within the fitted model and does not establish a causal relationship.

In [49]:
# Clean feature labels for visualisation

dt_plot = dt_used_features.copy()

dt_plot["Feature_Label"] = (
    dt_plot["Feature"]
    .str.replace("num__", "", regex=False)
    .str.replace("cat__", "", regex=False)
    .str.replace("_", " ", regex=False)
)

dt_plot = dt_plot.sort_values(
    "Importance",
    ascending=True
)

fig = px.bar(
    dt_plot,
    x="Importance",
    y="Feature_Label",
    orientation="h",
    text="Importance",
    labels={
        "Importance": "Feature Importance",
        "Feature_Label": "Predictor"
    },
    title="Feature Importance in the Tuned Decision Tree"
)

fig.update_traces(
    texttemplate="%{text:.3f}",
    textposition="outside"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    height=520,
    yaxis_title="",
    xaxis_title="Relative Feature Importance"
)

fig.show()

## Final Model Comparison

The final Logistic Regression and tuned Decision Tree were compared using their performance on the held-out test set. This comparison represents performance on observations that were not used during model training or hyperparameter optimisation.

In [50]:
# Final held-out model performance comparison

final_model_results = pd.DataFrame({
    "Model": [
        "Final Logistic Regression",
        "Tuned Decision Tree"
    ],
    "Accuracy": [
        final_lr_accuracy,
        0.707
    ],
    "Precision": [
        final_lr_precision,
        0.500
    ],
    "Recall": [
        final_lr_recall,
        0.500
    ],
    "F1": [
        final_lr_f1,
        0.500
    ],
    "ROC-AUC": [
        final_lr_auc,
        0.757
    ]
})

final_model_long = final_model_results.melt(
    id_vars="Model",
    var_name="Metric",
    value_name="Score"
)

fig = px.bar(
    final_model_long,
    x="Metric",
    y="Score",
    color="Model",
    barmode="group",
    text_auto=".3f",
    title="Final Held-Out Test Performance"
)

fig.update_layout(
    template="plotly_white",
    title_x=0.5,
    height=560,
    yaxis_title="Score",
    yaxis_range=[0, 1],
    legend_title="Model"
)

fig.show()

## Dataset Summary and Conclusion

This dataset contained 201 participants and examined workplace incivility, emotional exhaustion and adaptive performance alongside demographic and occupational characteristics. Emotional exhaustion was used as the burnout-related outcome. The validated nine-item EES score was transformed to a 0–100 Harmonised Burnout Score (HBS), and the dataset-specific 75th-percentile threshold of 50.0 was used to identify elevated risk. This resulted in 143 participants (71.1%) being classified as lower risk and 58 (28.9%) as elevated risk.

Following language verification, construct validation, preprocessing and exploratory analysis, ten predictors were retained for primary modelling. Sparse employment-sector and education categories were grouped where conceptually appropriate, while race was excluded from the primary model because of highly uneven representation across categories.

Exploratory analysis showed that workplace incivility was higher among elevated-risk participants, with mean WIS scores of 19.57 compared with 12.19 among lower-risk participants. Adaptive performance was somewhat lower among elevated-risk participants, while age showed little descriptive relationship with HBS.

Both Logistic Regression and Decision Tree models were developed using stratified training procedures and hyperparameter optimisation. The final Logistic Regression achieved a held-out accuracy of 0.756, precision of 0.571, recall of 0.667, F1-score of 0.615 and ROC-AUC of 0.779. It correctly identified 8 of the 12 elevated-risk participants in the held-out test set. The tuned Decision Tree achieved an accuracy of 0.707, precision of 0.500, recall of 0.500, F1-score of 0.500 and ROC-AUC of 0.757, identifying 6 of the 12 elevated-risk participants.

Interpretability analysis showed a consistent cross-model pattern. Workplace incivility was the strongest retained predictor in the final Logistic Regression and the most influential feature in the tuned Decision Tree. In the Logistic Regression, a one-standard-deviation increase in WIS corresponded to approximately 2.48 times the modelled odds of elevated emotional-exhaustion risk, holding the other encoded features constant. WIS also accounted for 51.4% of the Decision Tree's impurity-based feature importance.

Overall, the results demonstrate moderate predictive capability for identifying elevated emotional-exhaustion risk within this dataset while retaining model interpretability. The findings indicate that workplace incivility was an important predictive feature across both interpretable models. These findings represent predictive associations within this sample and should not be interpreted as evidence of causality or as a clinical diagnosis of occupational burnout. The relatively small sample and held-out test set also require cautious interpretation of the reported performance estimates.

## Overall Model Performance Summary

The modelling stages were summarised to compare baseline cross-validation performance, tuned cross-validation performance and final held-out test performance. This provides an overview of how model optimisation affected performance while distinguishing between cross-validation estimates obtained during model development and final performance on unseen test observations.

In [51]:
# Final summary of model performance across all evaluation stages

performance_summary = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Logistic Regression",
        "Logistic Regression",
        "Decision Tree",
        "Decision Tree",
        "Decision Tree"
    ],
    "Evaluation Stage": [
        "Baseline CV",
        "Tuned CV",
        "Final Held-Out Test",
        "Baseline CV",
        "Tuned CV",
        "Final Held-Out Test"
    ],
    "Accuracy": [
        0.681, 0.681, 0.756,
        0.669, 0.744, 0.707
    ],
    "Precision": [
        0.439, 0.468, 0.571,
        0.437, 0.530, 0.500
    ],
    "Recall": [
        0.578, 0.627, 0.667,
        0.391, 0.689, 0.500
    ],
    "F1": [
        0.480, 0.527, 0.615,
        0.409, 0.590, 0.500
    ],
    "ROC-AUC": [
        0.695, 0.714, 0.779,
        0.586, 0.758, 0.757
    ]
})

# Display as a polished notebook table
(
    performance_summary
    .style
    .format({
        "Accuracy": "{:.3f}",
        "Precision": "{:.3f}",
        "Recall": "{:.3f}",
        "F1": "{:.3f}",
        "ROC-AUC": "{:.3f}"
    })
    .set_caption("Overall Model Performance Across Evaluation Stages")
    .background_gradient(
        subset=["Accuracy", "Precision", "Recall", "F1", "ROC-AUC"],
        cmap="Blues"
    )
    .set_properties(**{
        "text-align": "center",
        "padding": "10px"
    })
    .set_table_styles([
        {
            "selector": "caption",
            "props": [
                ("font-size", "18px"),
                ("font-weight", "bold"),
                ("text-align", "center"),
                ("padding", "12px")
            ]
        },
        {
            "selector": "th",
            "props": [
                ("text-align", "center"),
                ("font-weight", "bold"),
                ("padding", "10px")
            ]
        },
        {
            "selector": "td",
            "props": [
                ("text-align", "center")
            ]
        }
    ])
    .hide(axis="index")
)

### Logistic Regression Statistical Inference

A separate inferential Logistic Regression analysis was conducted to complement the predictive modelling results. The researcher-validated predictor set used in the primary modelling analysis was retained.

Coefficients, odds ratios, 95% confidence intervals and p-values were estimated to examine adjusted associations between individual predictors and elevated burnout risk. Statistical significance was assessed at p < 0.05 and interpreted as supplementary to predictive performance and model interpretability rather than as evidence of causality.

In [52]:
# Check sample completeness before inferential Logistic Regression

inference_check = workplace[
    final_predictors + ["Burnout_Risk"]
].copy()

complete_inference = inference_check.dropna()

print("Original sample size:", len(inference_check))
print("Complete-case sample size:", len(complete_inference))
print(
    "Observations removed:",
    len(inference_check) - len(complete_inference)
)

print("\nComplete-case outcome distribution:")
print(
    complete_inference["Burnout_Risk"]
    .value_counts()
    .sort_index()
)

print("\nPredictors with missing values:")
missing_counts = (
    inference_check[final_predictors]
    .isna()
    .sum()
)

print(
    missing_counts[
        missing_counts > 0
    ].sort_values(ascending=False)
)

Original sample size: 201
Complete-case sample size: 201
Observations removed: 0

Complete-case outcome distribution:
Burnout_Risk
0    143
1     58
Name: count, dtype: int64

Predictors with missing values:
Series([], dtype: int64)

In [55]:
categorical_predictors = [
    "Gender_English",
    "Marital_Status_English",
    "Education_Grouped",
    "Employment_Sector_Grouped",
    "Rank_English",
    "Tenure_English",
    "Location_English"
]

In [56]:
for column in categorical_predictors:
    print(f"\n{'='*80}")
    print(column)
    print("="*80)

    print(
        pd.crosstab(
            complete_inference[column],
            complete_inference["Burnout_Risk"],
            margins=True
        )
    )

================================================================================
Gender_English
================================================================================
Burnout_Risk      0   1  All
Gender_English
Female          101  41  142
Male             42  17   59
All             143  58  201

================================================================================
Marital_Status_English
================================================================================
Burnout_Risk              0   1  All
Marital_Status_English
Divorced                  5   1    6
Married                  98  38  136
Single                   40  19   59
All                     143  58  201

================================================================================
Education_Grouped
================================================================================
Burnout_Risk         0   1  All
Education_Grouped
Degree              99  36  135
Diploma             22  16   38
Pre-tertiary         6   3    9
SPM                 16   3   19
All                143  58  201

================================================================================
Employment_Sector_Grouped
================================================================================
Burnout_Risk                 0   1  All
Employment_Sector_Grouped
Education                   55  17   72
Health                      55  30   85
Other                        7   2    9
Security                    10   3   13
Services                    16   6   22
All                        143  58  201

================================================================================
Rank_English
================================================================================
Burnout_Risk                   0   1  All
Rank_English
Professional and managerial   79  25  104
Support                       64  33   97
All                          143  58  201

================================================================================
Tenure_English
================================================================================
Burnout_Risk      0   1  All
Tenure_English
1-5 years        44  15   59
11-15 years      37  13   50
16-20 years       9   0    9
6-10 years       33  22   55
>20 years        20   8   28
All             143  58  201

================================================================================
Location_English
================================================================================
Burnout_Risk        0   1  All
Location_English
Rural              32  11   43
Urban             111  47  158
All               143  58  201

#### Sparse Category Handling

Category frequencies were examined before fitting the inferential Logistic Regression model. The 16–20 years tenure category contained nine observations, all of which belonged to the lower-risk group, creating a risk of complete separation and unstable maximum-likelihood estimation.

For the inferential analysis only, this ordered tenure category was combined with the adjacent >20 years category to form a broader 16+ years group. The primary predictive modelling analysis remained unchanged.

In [57]:
# Create inferential dataset with stable tenure grouping

workplace_inference = complete_inference.copy()

workplace_inference["Tenure_Inference"] = (
    workplace_inference["Tenure_English"]
    .replace({
        "16-20 years": "16+ years",
        ">20 years": "16+ years"
    })
)

print(
    pd.crosstab(
        workplace_inference["Tenure_Inference"],
        workplace_inference["Burnout_Risk"],
        margins=True
    )
)

Burnout_Risk        0   1  All
Tenure_Inference
1-5 years          44  15   59
11-15 years        37  13   50
16+ years          29   8   37
6-10 years         33  22   55
All               143  58  201

In [58]:
# Prepare final design matrix for inferential Logistic Regression

inferential_predictors = [
    "Age",
    "WIS",
    "API",
    "Gender_English",
    "Marital_Status_English",
    "Education_Grouped",
    "Employment_Sector_Grouped",
    "Rank_English",
    "Tenure_Inference",
    "Location_English"
]

X_workplace_inference = workplace_inference[
    inferential_predictors
].copy()

y_workplace_inference = workplace_inference[
    "Burnout_Risk"
].astype(int)

# Categorical predictors used in inferential model
categorical_inference = [
    "Gender_English",
    "Marital_Status_English",
    "Education_Grouped",
    "Employment_Sector_Grouped",
    "Rank_English",
    "Tenure_Inference",
    "Location_English"
]

# Dummy-code categorical predictors
X_workplace_inference = pd.get_dummies(
    X_workplace_inference,
    columns=categorical_inference,
    drop_first=True,
    dtype=float
)

# Ensure all predictors are numeric
X_workplace_inference = X_workplace_inference.astype(float)

print("Final inferential sample size:",
      len(X_workplace_inference))

print("Number of predictors after dummy coding:",
      X_workplace_inference.shape[1])

print("\nAny missing values:",
      X_workplace_inference.isna().sum().sum())

print("\nPredictor columns:")
for col in X_workplace_inference.columns:
    print("-", col)

Final inferential sample size: 201
Number of predictors after dummy coding: 18

Any missing values: 0

Predictor columns:
- Age
- WIS
- API
- Gender_English_Male
- Marital_Status_English_Married
- Marital_Status_English_Single
- Education_Grouped_Diploma
- Education_Grouped_Pre-tertiary
- Education_Grouped_SPM
- Employment_Sector_Grouped_Health
- Employment_Sector_Grouped_Other
- Employment_Sector_Grouped_Security
- Employment_Sector_Grouped_Services
- Rank_English_Support
- Tenure_Inference_11-15 years
- Tenure_Inference_16+ years
- Tenure_Inference_6-10 years
- Location_English_Urban

In [59]:
import statsmodels.api as sm

# Add intercept
X_workplace_inference_sm = sm.add_constant(
    X_workplace_inference
)

# Fit inferential Logistic Regression
workplace_inferential_lr = sm.Logit(
    y_workplace_inference,
    X_workplace_inference_sm
).fit(maxiter=100)

print(workplace_inferential_lr.summary())

Optimization terminated successfully.
         Current function value: 0.487151
         Iterations 6
                           Logit Regression Results
==============================================================================
Dep. Variable:           Burnout_Risk   No. Observations:                  201
Model:                          Logit   Df Residuals:                      182
Method:                           MLE   Df Model:                           18
Date:                Wed, 07 Oct 2026   Pseudo R-squ.:                  0.1892
Time:                        13:16:11   Log-Likelihood:                -97.917
converged:                       True   LL-Null:                       -120.77
Covariance Type:            nonrobust   LLR p-value:                 0.0003271
======================================================================================================
                                         coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------------
const                                 -3.4813      2.574     -1.352      0.176      -8.526       1.564
Age                                    0.0179      0.044      0.412      0.680      -0.067       0.103
WIS                                    0.1189      0.025      4.698      0.000       0.069       0.169
API                                   -0.0180      0.018     -1.012      0.312      -0.053       0.017
Gender_English_Male                   -0.1886      0.482     -0.391      0.695      -1.133       0.756
Marital_Status_English_Married         0.5349      1.277      0.419      0.675      -1.967       3.037
Marital_Status_English_Single          0.6784      1.364      0.497      0.619      -1.995       3.352
Education_Grouped_Diploma             -0.1246      0.578     -0.216      0.829      -1.257       1.008
Education_Grouped_Pre-tertiary        -0.4424      0.973     -0.455      0.649      -2.350       1.465
Education_Grouped_SPM                 -1.1025      0.857     -1.286      0.198      -2.783       0.578
Employment_Sector_Grouped_Health       0.4796      0.509      0.942      0.346      -0.518       1.477
Employment_Sector_Grouped_Other        0.3529      0.953      0.370      0.711      -1.515       2.220
Employment_Sector_Grouped_Security     0.1338      0.932      0.144      0.886      -1.693       1.960
Employment_Sector_Grouped_Services     0.2005      0.697      0.288      0.774      -1.165       1.566
Rank_English_Support                   0.5276      0.413      1.279      0.201      -0.281       1.336
Tenure_Inference_11-15 years           0.6359      0.691      0.920      0.357      -0.719       1.990
Tenure_Inference_16+ years             0.3038      1.019      0.298      0.766      -1.694       2.301
Tenure_Inference_6-10 years            0.9828      0.551      1.784      0.074      -0.097       2.062
Location_English_Urban                 0.2895      0.480      0.603      0.546      -0.651       1.230
======================================================================================================

In [60]:
# Create inferential results table for Workplace Incivility dataset

workplace_ci = workplace_inferential_lr.conf_int()

workplace_inference_results = pd.DataFrame({
    "Predictor": workplace_inferential_lr.params.index,
    "Coefficient": workplace_inferential_lr.params.values,
    "Odds Ratio": np.exp(workplace_inferential_lr.params.values),
    "CI Lower": np.exp(workplace_ci[0].values),
    "CI Upper": np.exp(workplace_ci[1].values),
    "p-value": workplace_inferential_lr.pvalues.values
})

# Remove intercept
workplace_inference_results = workplace_inference_results[
    workplace_inference_results["Predictor"] != "const"
].copy()

workplace_inference_results["Significant (p < 0.05)"] = np.where(
    workplace_inference_results["p-value"] < 0.05,
    "Yes",
    "No"
)

workplace_inference_results["95% CI for OR"] = (
    workplace_inference_results["CI Lower"].map("{:.3f}".format)
    + " – "
    + workplace_inference_results["CI Upper"].map("{:.3f}".format)
)

workplace_inference_table = workplace_inference_results[
    [
        "Predictor",
        "Coefficient",
        "Odds Ratio",
        "95% CI for OR",
        "p-value",
        "Significant (p < 0.05)"
    ]
]

display(
    workplace_inference_table.style
    .format({
        "Coefficient": "{:.3f}",
        "Odds Ratio": "{:.3f}",
        "p-value": lambda x: "<0.001" if x < 0.001 else f"{x:.3f}"
    })
    .background_gradient(
        subset=["Odds Ratio"],
        cmap="Blues"
    )
    .set_caption(
        "Inferential Logistic Regression Results – Workplace Incivility Dataset"
    )
    .hide(axis="index")
)

#### Statistical Interpretation

The inferential Logistic Regression model was statistically significant overall (likelihood-ratio p < 0.001), indicating that the predictor set collectively showed evidence of association with elevated burnout risk.

Workplace incivility (WIS) was the only predictor demonstrating a statistically significant independent association with elevated burnout risk (β = 0.119, p < 0.001). The corresponding odds ratio indicates that each one-unit increase in WIS was associated with approximately 12.6% higher odds of elevated burnout risk, holding the remaining predictors constant.

The demographic, occupational and adaptive-performance predictors did not demonstrate statistically significant independent associations after multivariable adjustment. The 6–10 year tenure category approached, but did not meet, the predefined significance threshold (p = 0.074).

These findings represent adjusted statistical associations rather than causal effects. Statistical significance is interpreted as supplementary to the primary predictive modelling results and does not independently indicate predictive importance or model performance.